blueprint:
  name: MQTT Lamp Schakelaar
  description: Schakel een lamp aan of uit op basis van een MQTT-trigger.
  domain: automation
  input:
    mqtt_topic:
      name: MQTT-topic
      description: Het MQTT-topic dat de trigger activeert.
      default: "zigbee2mqtt/testknop/action"
      selector:
        text:
    lamp:
      name: Lamp
      description: De lamp die in- of uitgeschakeld moet worden.
      selector:
        target:
          entity:
            domain: light

triggers:
  - platform: mqtt
    topic: !input 'mqtt_topic'
    payload: "on"

action:
  - service: light.toggle
    target: !input 'lamp'

mode: single
