blueprint:
  name: Lamp Kleur en Tijdsduur Schakelaar met Knop
  description: Verander de kleur van een lamp voor een bepaalde tijd met een knopdruk.
  domain: automation
  input:
    trigger_button:
      name: Activeringsknop
      description: Selecteer de knop die de lamp van kleur laat veranderen.
      selector:
        entity:
          domain: sensor  # Dit kan ook "button" zijn, afhankelijk van je integratie.
    lamp:
      name: Lamp
      description: Selecteer de lamp die van kleur verandert.
      selector:
        target:
          entity:
            domain: light
    kleur:
      name: Kleur
      description: Selecteer de kleur waarin de lamp moet veranderen.
      selector:
        color_rgb: {}
    duration:
      name: Tijdsduur (seconden)
      description: De tijd dat de lamp in de gekozen kleur blijft.
      default: 10
      selector:
        number:
          min: 1
          max: 600
          unit_of_measurement: seconden

trigger:
  - platform: state
    entity_id: !input 'trigger_button'
    to: "on"  # Afhankelijk van je knop kan dit worden aangepast

action:
  - variables:
      previous_state: "{{ states(!input 'lamp') }}"
      
  - service: light.turn_on
    target: !input 'lamp'
    data:
      rgb_color: !input 'kleur'

  - delay: !input 'duration'

  - service: light.turn_on
    target: !input 'lamp'
    data:
      brightness: "{{ previous_state.attributes.brightness }}"
      rgb_color: "{{ previous_state.attributes.rgb_color }}"
      state: "{{ previous_state.state }}"

mode: single
