blueprint:
  name: Lamp Kleur Verandering met Timer
  description: Sla de status van een lamp op en verander deze in een ingestelde kleur voor een bepaalde tijd.
  domain: automation
  input:
    trigger_button:
      name: Activeringsknop
      description: Selecteer de knop die de actie start.
      selector:
        entity:
          domain: sensor
    lamp:
      name: Lamp
      description: Selecteer de lamp die van status moet veranderen.
      selector:
        entity:
          domain: light
    kleur:
      name: Kleur
      description: Selecteer de kleur waarin de lamp moet veranderen.
      selector:
        color_rgb: {}
    delay_duration:
      name: Tijd voor statusopslag (minuten)
      description: Hoe lang de oorspronkelijke status moet worden opgeslagen voordat de lamp van kleur verandert.
      default: 10
      selector:
        number:
          min: 1
          max: 60
          unit_of_measurement: minuten
    on_duration:
      name: Lamp actief tijdsduur (seconden)
      description: Hoe lang de lamp in de nieuwe kleur moet blijven.
      default: 30
      selector:
        number:
          min: 1
          max: 600
          unit_of_measurement: seconden

trigger:
  - platform: state
    entity_id: !input 'trigger_button'

variables:
  lamp_entity: "{{ states['' + !input 'lamp'] }}"  # Definieert lamp_entity op basis van de geselecteerde lamp
  original_state: "{{ lamp_entity.state }}"  # Sla de oorspronkelijke status op (aan/uit)
  original_brightness: "{{ state_attr(lamp_entity.entity_id, 'brightness') if state_attr(lamp_entity.entity_id, 'brightness') is not none else 255 }}"  # Sla de oorspronkelijke helderheid op
  original_rgb_color: "{{ state_attr(lamp_entity.entity_id, 'rgb_color') if state_attr(lamp_entity.entity_id, 'rgb_color') is not none else [255, 255, 255] }}"  # Sla de oorspronkelijke kleur op

action:
  - delay:
      minutes: !input 'delay_duration'  # Wacht de ingestelde tijd om de oorspronkelijke status te behouden

  - service: light.turn_on  # Schakel de lamp in met de nieuwe kleur
    target:
      entity_id: !input 'lamp'
    data:
      rgb_color: !input 'kleur'

  - delay:
      seconds: !input 'on_duration'  # Wacht de ingestelde tijd voordat de lamp teruggezet wordt

  - choose:
      - conditions:
          - condition: template
            value_template: "{{ original_state == 'on' }}"
        sequence:
          - service: light.turn_on  # Herstel de oorspronkelijke status van de lamp (aan met vorige kleur en helderheid)
            target:
              entity_id: !input 'lamp'
            data:
              brightness: "{{ original_brightness }}"
              rgb_color: "{{ original_rgb_color }}"
      - conditions:
          - condition: template
            value_template: "{{ original_state == 'off' }}"
        sequence:
          - service: light.turn_off  # Schakel de lamp uit als deze oorspronkelijk uit stond
            target:
              entity_id: !input 'lamp'

mode: single
