blueprint:
  name: Ventilatiesysteem met Hysteresis en Verbeteringen (4 Ventilatoren) - Versie 256
  description: >
    Automatisering voor het bedienen van 4 ventilatoren in Woonkamer, Slaapkamer, Kantoor en Zolder.
    Elke kamer heeft een eigen gewenste temperatuur en optie voor uitschakeling bij regen.
    Inclusief update interval en minimale schakeltijd.
  domain: automation
  input:
    # Woonkamer
    fan_switch_woonkamer:
      name: Ventilator Woonkamer
      selector:
        entity:
          domain: switch
    temp_sensor_woonkamer:
      name: Temperatuursensor Woonkamer
      selector:
        entity:
          domain: sensor
          device_class: temperature
    desired_temp_woonkamer:
      name: Gewenste Kamertemperatuur Woonkamer
      default: 21.0
      selector:
        number:
          min: 10
          max: 30
          step: 0.5
          unit_of_measurement: "°C"
          mode: slider
    disable_rain_shutdown_woonkamer:
      name: Uitschakeling bij Regen voor Woonkamer
      description: "Schakel ventilator uit bij regen."
      default: false
      selector:
        boolean: {}

    # Slaapkamer
    fan_switch_slaapkamer:
      name: Ventilator Slaapkamer
      selector:
        entity:
          domain: switch
    temp_sensor_slaapkamer:
      name: Temperatuursensor Slaapkamer
      selector:
        entity:
          domain: sensor
          device_class: temperature
    desired_temp_slaapkamer:
      name: Gewenste Kamertemperatuur Slaapkamer
      default: 21.0
      selector:
        number:
          min: 10
          max: 30
          step: 0.5
          unit_of_measurement: "°C"
          mode: slider
    disable_rain_shutdown_slaapkamer:
      name: Uitschakeling bij Regen voor Slaapkamer
      default: false
      selector:
        boolean: {}

    # Kantoor
    fan_switch_kantoor:
      name: Ventilator Kantoor
      selector:
        entity:
          domain: switch
    temp_sensor_kantoor:
      name: Temperatuursensor Kantoor
      selector:
        entity:
          domain: sensor
          device_class: temperature
    desired_temp_kantoor:
      name: Gewenste Kamertemperatuur Kantoor
      default: 21.0
      selector:
        number:
          min: 10
          max: 30
          step: 0.5
          unit_of_measurement: "°C"
          mode: slider
    disable_rain_shutdown_kantoor:
      name: Uitschakeling bij Regen voor Kantoor
      default: false
      selector:
        boolean: {}

    # Zolder
    fan_switch_zolder:
      name: Ventilator Zolder
      selector:
        entity:
          domain: switch
    temp_sensor_zolder:
      name: Temperatuursensor Zolder
      selector:
        entity:
          domain: sensor
          device_class: temperature
    desired_temp_zolder:
      name: Gewenste Kamertemperatuur Zolder
      default: 21.0
      selector:
        number:
          min: 10
          max: 30
          step: 0.5
          unit_of_measurement: "°C"
          mode: slider
    disable_rain_shutdown_zolder:
      name: Uitschakeling bij Regen voor Zolder
      default: false
      selector:
        boolean: {}

    # Algemene instellingen
    weather_sensor:
      name: Weersensor
      description: "Buitentemperatuur en regenmeting."
      selector:
        entity:
          domain: weather
    hysteresis_value:
      name: Hysteresis Waarde
      description: "De marge om te voorkomen dat de ventilator te snel schakelt."
      default: 0.5
      selector:
        number:
          min: 0.1
          max: 5.0
          step: 0.1
          unit_of_measurement: "°C"
          mode: slider

    rain_threshold_value:
      name: Neerslagdrempel
      description: >
        Minimale hoeveelheid neerslag om de ventilator uit te schakelen. Waarden zijn bijvoorbeeld:
        - Motregen: 0.1 mm
        - Regen: 0.5 mm
        - Harde Regen: 2.0 mm
      default: 0.1
      selector:
        number:
          min: 0.0
          max: 5.0
          step: 0.1
          unit_of_measurement: "mm"
          mode: slider

    # Update Interval en Minimale Schakeltijd
    update_interval:
      name: Update Interval
      description: "Hoe vaak de automatisering controleert (in minuten)."
      default: 5
      selector:
        number:
          min: 1
          max: 15
          step: 1
          unit_of_measurement: "minuten"
          mode: slider

    minimale_schakeltijd:
      name: Minimale Schakeltijd
      description: "Minimale tijd (in minuten) dat een ventilator aan of uit moet blijven voordat deze weer mag schakelen."
      default: 10
      selector:
        number:
          min: 1
          max: 60
          step: 1
          unit_of_measurement: "minuten"
          mode: slider

variables:
  # Woonkamer variabelen
  fan_switch_woonkamer_entity_id: !input 'fan_switch_woonkamer'
  temp_sensor_woonkamer_entity_id: !input 'temp_sensor_woonkamer'
  desired_temp_woonkamer_value: !input 'desired_temp_woonkamer'
  disable_rain_shutdown_woonkamer_value: !input 'disable_rain_shutdown_woonkamer'

  # Slaapkamer variabelen
  fan_switch_slaapkamer_entity_id: !input 'fan_switch_slaapkamer'
  temp_sensor_slaapkamer_entity_id: !input 'temp_sensor_slaapkamer'
  desired_temp_slaapkamer_value: !input 'desired_temp_slaapkamer'
  disable_rain_shutdown_slaapkamer_value: !input 'disable_rain_shutdown_slaapkamer'

  # Kantoor variabelen
  fan_switch_kantoor_entity_id: !input 'fan_switch_kantoor'
  temp_sensor_kantoor_entity_id: !input 'temp_sensor_kantoor'
  desired_temp_kantoor_value: !input 'desired_temp_kantoor'
  disable_rain_shutdown_kantoor_value: !input 'disable_rain_shutdown_kantoor'

  # Zolder variabelen
  fan_switch_zolder_entity_id: !input 'fan_switch_zolder'
  temp_sensor_zolder_entity_id: !input 'temp_sensor_zolder'
  desired_temp_zolder_value: !input 'desired_temp_zolder'
  disable_rain_shutdown_zolder_value: !input 'disable_rain_shutdown_zolder'

  # Algemene variabelen
  weather_entity_id: !input 'weather_sensor'
  hysteresis_value: !input 'hysteresis_value'
  rain_threshold_value: !input 'rain_threshold_value'
  update_interval_value: !input 'update_interval'
  minimale_schakeltijd_value: !input 'minimale_schakeltijd'

  # Sensorgegevens
  buiten_temp: >
    {% set temp = state_attr(weather_entity_id, 'temperature') %}
    {% if temp is not none %}
      {{ temp | float }}
    {% else %}
      {{ states('sensor.last_known_buiten_temp') | float(15.0) }}
    {% endif %}

  neerslag: >
    {% set rain = state_attr(weather_entity_id, 'precipitation') %}
    {% if rain is not none %}
      {{ rain | float }}
    {% else %}
      0
    {% endif %}

  # Tijdstempels voor minimale schakeltijd
  current_time: "{{ now() | as_timestamp }}"
  last_changed_woonkamer: "{{ states.switch.ventilator_woonkamer.last_changed | as_timestamp }}"
  last_changed_slaapkamer: "{{ states.switch.ventilator_slaapkamer.last_changed | as_timestamp }}"
  last_changed_kantoor: "{{ states.switch.ventilator_kantoor.last_changed | as_timestamp }}"
  last_changed_zolder: "{{ states.switch.ventilator_zolder.last_changed | as_timestamp }}"

trigger:
  - platform: time_pattern
    minutes: "/{{ update_interval_value }}"

  - platform: state
    entity_id:
      - !input 'temp_sensor_woonkamer'
      - !input 'temp_sensor_slaapkamer'
      - !input 'temp_sensor_kantoor'
      - !input 'temp_sensor_zolder'
      - !input 'weather_sensor'

action:
  - service: system_log.write
    data:
      message: >
        "Ventilatiecontrole uitgevoerd. Buiten temp: {{ buiten_temp }}°C,
        Woonkamer temp: {{ states(temp_sensor_woonkamer_entity_id) }}°C,
        Slaapkamer temp: {{ states(temp_sensor_slaapkamer_entity_id) }}°C,
        Kantoor temp: {{ states(temp_sensor_kantoor_entity_id) }}°C,
        Zolder temp: {{ states(temp_sensor_zolder_entity_id) }}°C,
        Neerslag: {{ neerslag }} mm."

  # Voor Woonkamer
  - choose:
      - conditions:
          - condition: template
            value_template: "{{ neerslag >= rain_threshold_value and not disable_rain_shutdown_woonkamer_value }}"
        sequence:
          - service: switch.turn_off
            target:
              entity_id: !input 'fan_switch_woonkamer'
          - service: system_log.write
            data:
              message: "Ventilator Woonkamer uitgeschakeld vanwege regen."

      - conditions:
          - condition: template
            value_template: "{{ states(temp_sensor_woonkamer_entity_id) | float >= desired_temp_woonkamer_value + hysteresis_value and buiten_temp < states(temp_sensor_woonkamer_entity_id) | float }}"
        sequence:
          - service: switch.turn_on
            target:
              entity_id: !input 'fan_switch_woonkamer'
          - service: system_log.write
            data:
              message: "Ventilator Woonkamer ingeschakeld."

      - conditions:
          - condition: template
            value_template: >
              {{ current_time - last_changed_woonkamer >= minimale_schakeltijd_value * 60 and
              buiten_temp >= states(temp_sensor_woonkamer_entity_id) | float }}
        sequence:
          - service: switch.turn_off
            target:
              entity_id: !input 'fan_switch_woonkamer'
          - service: system_log.write
            data:
              message: "Ventilator Woonkamer uitgeschakeld vanwege hoge buitentemperatuur en minimale schakeltijd."

  # Voor Slaapkamer
  - choose:
      - conditions:
          - condition: template
            value_template: "{{ neerslag >= rain_threshold_value and not disable_rain_shutdown_slaapkamer_value }}"
        sequence:
          - service: switch.turn_off
            target:
              entity_id: !input 'fan_switch_slaapkamer'
          - service: system_log.write
            data:
              message: "Ventilator Slaapkamer uitgeschakeld vanwege regen."

      - conditions:
          - condition: template
            value_template: "{{ states(temp_sensor_slaapkamer_entity_id) | float >= desired_temp_slaapkamer_value + hysteresis_value and buiten_temp < states(temp_sensor_slaapkamer_entity_id) | float }}"
        sequence:
          - service: switch.turn_on
            target:
              entity_id: !input 'fan_switch_slaapkamer'
          - service: system_log.write
            data:
              message: "Ventilator Slaapkamer ingeschakeld."

      - conditions:
          - condition: template
            value_template: >
              {{ current_time - last_changed_slaapkamer >= minimale_schakeltijd_value * 60 and
              buiten_temp >= states(temp_sensor_slaapkamer_entity_id) | float }}
        sequence:
          - service: switch.turn_off
            target:
              entity_id: !input 'fan_switch_slaapkamer'
          - service: system_log.write
            data:
              message: "Ventilator Slaapkamer uitgeschakeld vanwege hoge buitentemperatuur en minimale schakeltijd."

  # Voor Kantoor
  - choose:
      - conditions:
          - condition: template
            value_template: "{{ neerslag >= rain_threshold_value and not disable_rain_shutdown_kantoor_value }}"
        sequence:
          - service: switch.turn_off
            target:
              entity_id: !input 'fan_switch_kantoor'
          - service: system_log.write
            data:
              message: "Ventilator Kantoor uitgeschakeld vanwege regen."

      - conditions:
          - condition: template
            value_template: "{{ states(temp_sensor_kantoor_entity_id) | float >= desired_temp_kantoor_value + hysteresis_value and buiten_temp < states(temp_sensor_kantoor_entity_id) | float }}"
        sequence:
          - service: switch.turn_on
            target:
              entity_id: !input 'fan_switch_kantoor'
          - service: system_log.write
            data:
              message: "Ventilator Kantoor ingeschakeld."

      - conditions:
          - condition: template
            value_template: >
              {{ current_time - last_changed_kantoor >= minimale_schakeltijd_value * 60 and
              buiten_temp >= states(temp_sensor_kantoor_entity_id) | float }}
        sequence:
          - service: switch.turn_off
            target:
              entity_id: !input 'fan_switch_kantoor'
          - service: system_log.write
            data:
              message: "Ventilator Kantoor uitgeschakeld vanwege hoge buitentemperatuur en minimale schakeltijd."

  # Voor Zolder
  - choose:
      - conditions:
          - condition: template
            value_template: "{{ neerslag >= rain_threshold_value and not disable_rain_shutdown_zolder_value }}"
        sequence:
          - service: switch.turn_off
            target:
              entity_id: !input 'fan_switch_zolder'
          - service: system_log.write
            data:
              message: "Ventilator Zolder uitgeschakeld vanwege regen."

      - conditions:
          - condition: template
            value_template: "{{ states(temp_sensor_zolder_entity_id) | float >= desired_temp_zolder_value + hysteresis_value and buiten_temp < states(temp_sensor_zolder_entity_id) | float }}"
        sequence:
          - service: switch.turn_on
            target:
              entity_id: !input 'fan_switch_zolder'
          - service: system_log.write
            data:
              message: "Ventilator Zolder ingeschakeld."

      - conditions:
          - condition: template
            value_template: >
              {{ current_time - last_changed_zolder >= minimale_schakeltijd_value * 60 and
              buiten_temp >= states(temp_sensor_zolder_entity_id) | float }}
        sequence:
          - service: switch.turn_off
            target:
              entity_id: !input 'fan_switch_zolder'
          - service: system_log.write
            data:
              message: "Ventilator Zolder uitgeschakeld vanwege hoge buitentemperatuur en minimale schakeltijd."

mode: single
