blueprint:
  name: Ventilatiesysteem met Hysteresis en Tweaks (4 Ventilatoren) - Versie 2.61
  description: >
    Dit script regelt de ventilatie in meerdere kamers op basis van de binnentemperatuur, buitentemperatuur, neerslag en hysteresis. Elke ventilator kan individueel worden ingesteld en er zijn tweaks voor schakeltijd en neerslagdrempel.

    **Versie**: 2.61

    **Te vinden op GitHub**: [Ventilatiesysteem 2.61](https://github.com/bibabouke/homeassistant/tree/main/blueprints/gebouwbeheersysteem)

  domain: automation
  input:

    # Sectie Ventilatoren
    ventilator_section:
      name: Ventilatoren
      icon: mdi:fan
      input:
        fan_switch_woonkamer:
          name: Ventilator Woonkamer
          selector:
            entity:
              domain: switch
        temp_sensor_woonkamer:
          name: Temperatuursensor Woonkamer
          selector:
            entity:
              domain: sensor
              device_class: temperature
        desired_temp_woonkamer:
          name: Gewenste Kamertemperatuur Woonkamer
          default: 21.0
          selector:
            number:
              min: 10
              max: 30
              step: 0.5
              unit_of_measurement: "°C"
        disable_rain_shutdown_woonkamer:
          name: Regenuitschakeling voor Woonkamer
          description: "Schakel ventilator uit bij regen."
          default: false
          selector:
            boolean: {}

        # Slaapkamer
        fan_switch_slaapkamer:
          name: Ventilator Slaapkamer
          selector:
            entity:
              domain: switch
        temp_sensor_slaapkamer:
          name: Temperatuursensor Slaapkamer
          selector:
            entity:
              domain: sensor
              device_class: temperature
        desired_temp_slaapkamer:
          name: Gewenste Kamertemperatuur Slaapkamer
          default: 21.0
          selector:
            number:
              min: 10
              max: 30
              step: 0.5
              unit_of_measurement: "°C"
        disable_rain_shutdown_slaapkamer:
          name: Regenuitschakeling voor Slaapkamer
          default: false
          selector:
            boolean: {}

        # Kantoor
        fan_switch_kantoor:
          name: Ventilator Kantoor
          selector:
            entity:
              domain: switch
        temp_sensor_kantoor:
          name: Temperatuursensor Kantoor
          selector:
            entity:
              domain: sensor
              device_class: temperature
        desired_temp_kantoor:
          name: Gewenste Kamertemperatuur Kantoor
          default: 21.0
          selector:
            number:
              min: 10
              max: 30
              step: 0.5
              unit_of_measurement: "°C"
        disable_rain_shutdown_kantoor:
          name: Regenuitschakeling voor Kantoor
          default: false
          selector:
            boolean: {}

        # Zolder
        fan_switch_zolder:
          name: Ventilator Zolder
          selector:
            entity:
              domain: switch
        temp_sensor_zolder:
          name: Temperatuursensor Zolder
          selector:
            entity:
              domain: sensor
              device_class: temperature
        desired_temp_zolder:
          name: Gewenste Kamertemperatuur Zolder
          default: 21.0
          selector:
            number:
              min: 10
              max: 30
              step: 0.5
              unit_of_measurement: "°C"
        disable_rain_shutdown_zolder:
          name: Regenuitschakeling voor Zolder
          default: false
          selector:
            boolean: {}

    # Sectie Weersensor
    weather_section:
      name: Weersensor
      icon: mdi:weather-partly-cloudy
      input:
        weather_sensor:
          name: Weersensor
          description: "Selecteer de weersensor voor buitentemperatuur en neerslag. Standaard is Buienradar."
          default: weather.buienradar
          selector:
            entity:
              domain: weather

    # Sectie Tweaks
    tweaks_section:
      name: Tweaks
      icon: mdi:tune
      input:
        hysteresis_value:
          name: Hysteresis Waarde
          description: "De marge om te voorkomen dat de ventilator te snel schakelt."
          default: 0.5
          selector:
            number:
              min: 0.1
              max: 5.0
              step: 0.1
              unit_of_measurement: "°C"
        rain_threshold_value:
          name: Neerslagdrempel
          description: "Minimale hoeveelheid neerslag om de ventilator uit te schakelen."
          default: 0.1
          selector:
            number:
              min: 0.0
              max: 5.0
              step: 0.1
              unit_of_measurement: "mm"
        minimale_schakeltijd_value:
          name: Minimale Schakeltijd
          description: "Minimale tijd (in minuten) dat een ventilator aan of uit moet blijven voordat deze weer mag schakelen."
          default: 10
          selector:
            number:
              min: 1
              max: 60
              step: 1
              unit_of_measurement: "minuten"

# Variables en logica om ventilatoren en sensoren te gebruiken
variables:
  fan_switch_woonkamer_entity_id: !input fan_switch_woonkamer
  temp_sensor_woonkamer_entity_id: !input temp_sensor_woonkamer
  desired_temp_woonkamer_value: !input desired_temp_woonkamer
  disable_rain_shutdown_woonkamer_value: !input disable_rain_shutdown_woonkamer
  # ... Herhaal voor de andere kamers

  weather_entity_id: !input weather_sensor
  hysteresis_value: !input hysteresis_value
  rain_threshold_value: !input rain_threshold_value
  minimale_schakeltijd_value: !input minimale_schakeltijd_value

  buiten_temp: >
    {% set temp = state_attr(weather_entity_id, 'temperature') %}
    {% if temp is not none %}
      {{ temp | float }}
    {% else %}
      {{ states('sensor.last_known_buiten_temp') | float(15.0) }}
    {% endif %}

  neerslag: >
    {% set rain = state_attr(weather_entity_id, 'precipitation') %}
    {% if rain is not none %}
      {{ rain | float }}
    {% else %}
      0
    {% endif %}

# Automatisering triggers en acties
trigger:
  - platform: time_pattern
    minutes: 5

action:
  - service: system_log.write
    data:
      message: >
        "Ventilatiecontrole uitgevoerd. Buiten temp: {{ buiten_temp }}°C, Woonkamer temp: {{ states(temp_sensor_woonkamer_entity_id) }}°C, Slaapkamer temp: {{ states(temp_sensor_slaapkamer_entity_id) }}°C, Kantoor temp: {{ states(temp_sensor_kantoor_entity_id) }}°C, Zolder temp: {{ states(temp_sensor_zolder_entity_id) }}°C, Neerslag: {{ neerslag }} mm."
      level: info

  - choose:
      # Logica voor Woonkamer, Slaapkamer, Kantoor, Zolder, gebaseerd op hysteresis en neerslagdrempel
      # Voeg de volledige logica voor alle kamers toe hier
