blueprint:
  name: Ventilatiesysteem met Hysteresis en Tweaks (4 Ventilatoren) - Versie 2.66
  description: >
    Dit script regelt de ventilatie in meerdere kamers op basis van de binnentemperatuur, buitentemperatuur, neerslag en hysteresis. Elke ventilator kan individueel worden ingesteld, en er zijn tweaks voor schakeltijd, regenuitschakeling en hysteresis.

    **Versie**: 2.66

  domain: automation
  input:

    # Sectie Ventilatoren
    ventilator_section:
      name: Ventilatoren
      description: "Configureer hier de ventilatoren en temperatuursensoren per kamer."
      selector:
        entity: {}
      input:
        fan_switch_woonkamer:
          name: Ventilator Woonkamer
          selector:
            entity:
              domain: switch
              optional: true
        temp_sensor_woonkamer:
          name: Temperatuursensor Woonkamer
          selector:
            entity:
              domain: sensor
              device_class: temperature
              optional: true
        desired_temp_woonkamer:
          name: Gewenste Kamertemperatuur Woonkamer
          default: 21.0
          selector:
            number:
              min: 10
              max: 30
              step: 0.5
              unit_of_measurement: "°C"
        disable_rain_shutdown_woonkamer:
          name: Regenuitschakeling voor Woonkamer
          description: "Schakel ventilator uit bij regen."
          default: false
          selector:
            boolean: {}

        fan_switch_slaapkamer:
          name: Ventilator Slaapkamer
          selector:
            entity:
              domain: switch
              optional: true
        temp_sensor_slaapkamer:
          name: Temperatuursensor Slaapkamer
          selector:
            entity:
              domain: sensor
              device_class: temperature
              optional: true
        desired_temp_slaapkamer:
          name: Gewenste Kamertemperatuur Slaapkamer
          default: 21.0
          selector:
            number:
              min: 10
              max: 30
              step: 0.5
              unit_of_measurement: "°C"
        disable_rain_shutdown_slaapkamer:
          name: Regenuitschakeling voor Slaapkamer
          default: false
          selector:
            boolean: {}

        fan_switch_kantoor:
          name: Ventilator Kantoor
          selector:
            entity:
              domain: switch
              optional: true
        temp_sensor_kantoor:
          name: Temperatuursensor Kantoor
          selector:
            entity:
              domain: sensor
              device_class: temperature
              optional: true
        desired_temp_kantoor:
          name: Gewenste Kamertemperatuur Kantoor
          default: 21.0
          selector:
            number:
              min: 10
              max: 30
              step: 0.5
              unit_of_measurement: "°C"
        disable_rain_shutdown_kantoor:
          name: Regenuitschakeling voor Kantoor
          default: false
          selector:
            boolean: {}

        fan_switch_zolder:
          name: Ventilator Zolder
          selector:
            entity:
              domain: switch
              optional: true
        temp_sensor_zolder:
          name: Temperatuursensor Zolder
          selector:
            entity:
              domain: sensor
              device_class: temperature
              optional: true
        desired_temp_zolder:
          name: Gewenste Kamertemperatuur Zolder
          default: 21.0
          selector:
            number:
              min: 10
              max: 30
              step: 0.5
              unit_of_measurement: "°C"
        disable_rain_shutdown_zolder:
          name: Regenuitschakeling voor Zolder
          default: false
          selector:
            boolean: {}

    # Sectie Weersensor
    weather_sensor:
      name: Weersensor
      description: "Selecteer de weersensor voor buitentemperatuur en neerslag. Standaard is Buienradar."
      default: weather.buienradar
      selector:
        entity:
          domain: weather

    # Sectie Tweaks
    tweaks_section:
      name: Tweaks
      description: "Hier kun je tweaks instellen zoals hysteresis, neerslagdrempel en schakeltijd."
      input:
        hysteresis_value:
          name: Hysteresis Waarde
          description: "De marge om te voorkomen dat de ventilator te snel schakelt."
          default: 0.5
          selector:
            number:
              min: 0.1
              max: 5.0
              step: 0.1
              unit_of_measurement: "°C"
        rain_threshold_value:
          name: Neerslagdrempel
          description: "Minimale hoeveelheid neerslag om de ventilator uit te schakelen."
          default: 0.1
          selector:
            number:
              min: 0.0
              max: 5.0
              step: 0.1
              unit_of_measurement: "mm"
        minimale_schakeltijd_value:
          name: Minimale Schakeltijd
          description: "Minimale tijd (in minuten) dat een ventilator aan of uit moet blijven voordat deze weer mag schakelen."
          default: 10
          selector:
            number:
              min: 1
              max: 60
              step: 1
              unit_of_measurement: "minuten"
        overworked_timer_value:
          name: Overwerktimer
          description: "Tijd (in minuten) dat het systeem handmatige schakelingen negeert bij een actieve overwerktimer."
          default: 15
          selector:
            number:
              min: 5
              max: 60
              step: 1
              unit_of_measurement: "minuten"

# Variabelen en fallback logica
variables:
  fan_switch_woonkamer_entity_id: !input fan_switch_woonkamer
  temp_sensor_woonkamer_entity_id: !input temp_sensor_woonkamer
  desired_temp_woonkamer_value: !input desired_temp_woonkamer
  disable_rain_shutdown_woonkamer_value: !input disable_rain_shutdown_woonkamer
  fan_switch_slaapkamer_entity_id: !input fan_switch_slaapkamer
  temp_sensor_slaapkamer_entity_id: !input temp_sensor_slaapkamer
  desired_temp_slaapkamer_value: !input desired_temp_slaapkamer
  disable_rain_shutdown_slaapkamer_value: !input disable_rain_shutdown_slaapkamer
  fan_switch_kantoor_entity_id: !input fan_switch_kantoor
  temp_sensor_kantoor_entity_id: !input temp_sensor_kantoor
  desired_temp_kantoor_value: !input desired_temp_kantoor
  disable_rain_shutdown_kantoor_value: !input disable_rain_shutdown_kantoor
  fan_switch_zolder_entity_id: !input fan_switch_zolder
  temp_sensor_zolder_entity_id: !input temp_sensor_zolder
  desired_temp_zolder_value: !input desired_temp_zolder
  disable_rain_shutdown_zolder_value: !input disable_rain_shutdown_zolder
  weather_entity_id: !input weather_sensor
  hysteresis_value: !input hysteresis_value
  rain_threshold_value: !input rain_threshold_value
  minimale_schakeltijd_value: !input minimale_schakeltijd_value
  overworked_timer_value: !input overworked_timer_value

  # Fallback logica voor kamers
  fallback_temp_woonkamer: "{{ states(temp_sensor_woonkamer_entity_id) | float(default=desired_temp_woonkamer_value) }}"
  fallback_temp_slaapkamer: "{{ states(temp_sensor_slaapkamer_entity_id) | float(default=desired_temp_slaapkamer_value) }}"
  fallback_temp_kantoor: "{{ states(temp_sensor_kantoor_entity_id) | float(default=desired_temp_kantoor_value) }}"
  fallback_temp_zolder: "{{ states(temp_sensor_zolder_entity_id) | float(default=desired_temp_zolder_value) }}"

  buiten_temp: >
    {% set temp = state_attr(weather_entity_id, 'temperature') %}
    {% if temp is not none %}
      {{ temp | float }}
    {% else %}
      {{ states('sensor.last_known_buiten_temp') | float(15.0) }}
    {% endif %}

  neerslag: >
    {% set rain = state_attr(weather_entity_id, 'precipitation') %}
    {% if rain is not none %}
      {{ rain | float }}
    {% else %}
      0
    {% endif %}
