blueprint:
  name: Ventilatiesysteem met Hysteresis en Tweaks (4 Ventilatoren) - Versie 2.68
  description: >
    Dit script regelt de ventilatie in meerdere kamers op basis van de binnentemperatuur, buitentemperatuur, neerslag en hysteresis. Elke ventilator kan individueel worden ingesteld, en er zijn tweaks voor schakeltijd, regenuitschakeling en hysteresis.

    **Versie**: 2.68

  domain: automation
  input:
    ventilator_section:
      name: Ventilatoren
      input:
        fan_switch_woonkamer:
          name: Ventilator Woonkamer
          selector:
            entity:
              domain: switch
              optional: true
        temp_sensor_woonkamer:
          name: Temperatuursensor Woonkamer
          selector:
            entity:
              domain: sensor
              device_class: temperature
              optional: true
        desired_temp_woonkamer:
          name: Gewenste Kamertemperatuur Woonkamer
          default: 21.0
          selector:
            number:
              min: 10
              max: 30
              step: 0.5
              unit_of_measurement: "°C"
        disable_rain_shutdown_woonkamer:
          name: Regenuitschakeling voor Woonkamer
          default: false
          selector:
            boolean: {}

        fan_switch_slaapkamer:
          name: Ventilator Slaapkamer
          selector:
            entity:
              domain: switch
              optional: true
        temp_sensor_slaapkamer:
          name: Temperatuursensor Slaapkamer
          selector:
            entity:
              domain: sensor
              device_class: temperature
              optional: true
        desired_temp_slaapkamer:
          name: Gewenste Kamertemperatuur Slaapkamer
          default: 21.0
          selector:
            number:
              min: 10
              max: 30
              step: 0.5
              unit_of_measurement: "°C"
        disable_rain_shutdown_slaapkamer:
          name: Regenuitschakeling voor Slaapkamer
          default: false
          selector:
            boolean: {}

        fan_switch_kantoor:
          name: Ventilator Kantoor
          selector:
            entity:
              domain: switch
              optional: true
        temp_sensor_kantoor:
          name: Temperatuursensor Kantoor
          selector:
            entity:
              domain: sensor
              device_class: temperature
              optional: true
        desired_temp_kantoor:
          name: Gewenste Kamertemperatuur Kantoor
          default: 21.0
          selector:
            number:
              min: 10
              max: 30
              step: 0.5
              unit_of_measurement: "°C"
        disable_rain_shutdown_kantoor:
          name: Regenuitschakeling voor Kantoor
          default: false
          selector:
            boolean: {}

        fan_switch_zolder:
          name: Ventilator Zolder
          selector:
            entity:
              domain: switch
              optional: true
        temp_sensor_zolder:
          name: Temperatuursensor Zolder
          selector:
            entity:
              domain: sensor
              device_class: temperature
              optional: true
        desired_temp_zolder:
          name: Gewenste Kamertemperatuur Zolder
          default: 21.0
          selector:
            number:
              min: 10
              max: 30
              step: 0.5
              unit_of_measurement: "°C"
        disable_rain_shutdown_zolder:
          name: Regenuitschakeling voor Zolder
          default: false
          selector:
            boolean: {}

    tweaks_section:
      name: Hysteresis en Tweaks
      input:
        hysteresis_value:
          name: Hysteresis Waarde
          description: "De marge om te voorkomen dat de ventilator te snel schakelt."
          default: 0.5
          selector:
            number:
              min: 0.1
              max: 5.0
              step: 0.1
              unit_of_measurement: "°C"
        rain_threshold_value:
          name: Neerslagdrempel
          description: "Minimale hoeveelheid neerslag om de ventilator uit te schakelen."
          default: 0.1
          selector:
            number:
              min: 0.0
              max: 5.0
              step: 0.1
              unit_of_measurement: "mm"
        minimum_duration:
          name: Minimale Duur
          description: "Minimale tijd die een ventilator aan moet staan voordat hij weer kan uitschakelen."
          default: 5
          selector:
            number:
              min: 1
              max: 60
              step: 1
              unit_of_measurement: "min"

    weather_section:
      name: Weersensoren
      input:
        weather_sensor:
          name: Weersensor
          selector:
            entity:
              domain: sensor
              device_class: temperature
              optional: true
