blueprint:
  name: Ventilatiesysteem met Hysteresis en Tweaks (4 Ventilatoren) - Versie 2.71
  description: >
    Dit script regelt de ventilatie in meerdere kamers op basis van de binnentemperatuur, buitentemperatuur, neerslag en hysteresis. Elke ventilator kan individueel worden ingesteld, en er zijn tweaks voor schakeltijd, regenuitschakeling en hysteresis.

    **Versie**: 2.71

  domain: automation
  input:
    ventilator_section:
      name: Ventilatoren
      input:
        fan_switch_woonkamer:
          name: Ventilator Woonkamer
          selector:
            entity:
              domain: switch
        temp_sensor_woonkamer:
          name: Temperatuursensor Woonkamer
          selector:
            entity:
              domain: sensor
              device_class: temperature
        desired_temp_woonkamer:
          name: Gewenste Kamertemperatuur Woonkamer
          default: 21.0
          selector:
            number:
              min: 10
              max: 30
              step: 0.5
              unit_of_measurement: "°C"
        disable_rain_shutdown_woonkamer:
          name: Regenuitschakeling voor Woonkamer
          description: "Schakel ventilator uit bij regen."
          default: false
          selector:
            boolean: {}

        fan_switch_slaapkamer:
          name: Ventilator Slaapkamer
          selector:
            entity:
              domain: switch
        temp_sensor_slaapkamer:
          name: Temperatuursensor Slaapkamer
          selector:
            entity:
              domain: sensor
              device_class: temperature
        desired_temp_slaapkamer:
          name: Gewenste Kamertemperatuur Slaapkamer
          default: 21.0
          selector:
            number:
              min: 10
              max: 30
              step: 0.5
              unit_of_measurement: "°C"

        fan_switch_kantoor:
          name: Ventilator Kantoor
          selector:
            entity:
              domain: switch
        temp_sensor_kantoor:
          name: Temperatuursensor Kantoor
          selector:
            entity:
              domain: sensor
              device_class: temperature
        desired_temp_kantoor:
          name: Gewenste Kamertemperatuur Kantoor
          default: 21.0
          selector:
            number:
              min: 10
              max: 30
              step: 0.5
              unit_of_measurement: "°C"

        fan_switch_zolder:
          name: Ventilator Zolder
          selector:
            entity:
              domain: switch
        temp_sensor_zolder:
          name: Temperatuursensor Zolder
          selector:
            entity:
              domain: sensor
              device_class: temperature
        desired_temp_zolder:
          name: Gewenste Kamertemperatuur Zolder
          default: 21.0
          selector:
            number:
              min: 10
              max: 30
              step: 0.5
              unit_of_measurement: "°C"

    weather_section:
      name: Weersensoren
      input:
        weather_sensor:
          name: Weersensor
          selector:
            entity:
              domain: sensor
              device_class: temperature

    tweaks_section:
      name: Tweaks
      input:
        hysteresis_value:
          name: Hysteresis Waarde
          description: "De marge om te voorkomen dat de ventilator te snel schakelt."
          default: 0.5
          selector:
            number:
              min: 0.1
              max: 5.0
              step: 0.1
              unit_of_measurement: '°C'
        rain_threshold_value:
          name: Neerslagdrempel
          description: "Minimale hoeveelheid neerslag om de ventilator uit te schakelen."
          default: 0.1
          selector:
            number:
              min: 0.0
              max: 5.0
              step: 0.1
              unit_of_measurement: 'mm'
        minimale_schakeltijd:
          name: Minimale Schakeltijd
          description: "Minimale tijd tussen twee schakelingen van de ventilator."
          default: 30
          selector:
            number:
              min: 10
              max: 120
              step: 1
              unit_of_measurement: 's'

  trigger:
    - platform: state
      entity_id:
        - sensor.thermostaat_woonkamer_binnentemperatuur
        - sensor.sensor_slaapkamer_temperature
        - sensor.sensor_kantoor_temperature
        - sensor.sensor_zolder_temperature

  condition:
    - condition: or
      conditions:
        - condition: numeric_state
          entity_id: sensor.thermostaat_woonkamer_binnentemperatuur
          above: '{{ input_number.desired_temp_woonkamer | float }}'
        - condition: numeric_state
          entity_id: sensor.sensor_slaapkamer_temperature
          above: '{{ input_number.desired_temp_slaapkamer | float }}'
        - condition: numeric_state
          entity_id: sensor.sensor_kantoor_temperature
          above: '{{ input_number.desired_temp_kantoor | float }}'
        - condition: numeric_state
          entity_id: sensor.sensor_zolder_temperature
          above: '{{ input_number.desired_temp_zolder | float }}'

  action:
    - choose:
        - conditions:
            - condition: numeric_state
              entity_id: sensor.thermostaat_woonkamer_binnentemperatuur
              above: '{{ input_number.desired_temp_woonkamer | float }}'
          sequence:
            - service: switch.turn_on
              target:
                entity_id: '{{ input.select.fan_switch_woonkamer }}'
        - conditions:
            - condition: numeric_state
              entity_id: sensor.sensor_slaapkamer_temperature
              above: '{{ input_number.desired_temp_slaapkamer | float }}'
          sequence:
            - service: switch.turn_on
              target:
                entity_id: '{{ input.select.fan_switch_slaapkamer }}'
        - conditions:
            - condition: numeric_state
              entity_id: sensor.sensor_kantoor_temperature
              above: '{{ input_number.desired_temp_kantoor | float }}'
          sequence:
            - service: switch.turn_on
              target:
                entity_id: '{{ input.select.fan_switch_kantoor }}'
        - conditions:
            - condition: numeric_state
              entity_id: sensor.sensor_zolder_temperature
              above: '{{ input_number.desired_temp_zolder | float }}'
          sequence:
            - service: switch.turn_on
              target:
                entity_id: '{{ input.select.fan_switch_zolder }}'
      default:
        - service: switch.turn_off
          target:
            entity_id: >
              {% if states('input.select.fan_switch_woonkamer') %}
                {{ input.select.fan_switch_woonkamer }}
              {% elif states('input.select.fan_switch_slaapkamer') %}
                {{ input.select.fan_switch_slaapkamer }}
              {% elif states('input.select.fan_switch_kantoor') %}
                {{ input.select.fan_switch_kantoor }}
              {% elif states('input.select.fan_switch_zolder') %}
                {{ input.select.fan_switch_zolder }}
              {% else %}
                none
              {% endif %}
