blueprint:
  name: Ventilatiesysteem met Hysteresis en Tweaks (4 Ventilatoren) - Versie 2.71
  description: >
    Dit script regelt de ventilatie in meerdere kamers op basis van de binnentemperatuur, buitentemperatuur, neerslag en hysteresis. Elke ventilator kan individueel worden ingesteld, en er zijn tweaks voor schakeltijd, regenuitschakeling en hysteresis.

    **Versie**: 2.71

  domain: automation
  input:
    ventilator_section:
      name: Ventilatoren
      description: Configureer de ventilatoren en temperatuursensoren
      input:
        fan_switch_woonkamer:
          name: Ventilator Woonkamer
          selector:
            entity:
              domain: switch
        temp_sensor_woonkamer:
          name: Temperatuursensor Woonkamer
          selector:
            entity:
              domain: sensor
              device_class: temperature
        desired_temp_woonkamer:
          name: Gewenste Kamertemperatuur Woonkamer
          default: 21.0
          selector:
            number:
              min: 10
              max: 30
              step: 0.5
              unit_of_measurement: "°C"
        disable_rain_shutdown_woonkamer:
          name: Regenuitschakeling voor Woonkamer
          description: "Schakel ventilator uit bij regen."
          default: false
          selector:
            boolean: {}

        fan_switch_slaapkamer:
          name: Ventilator Slaapkamer
          selector:
            entity:
              domain: switch
        temp_sensor_slaapkamer:
          name: Temperatuursensor Slaapkamer
          selector:
            entity:
              domain: sensor
              device_class: temperature
        desired_temp_slaapkamer:
          name: Gewenste Kamertemperatuur Slaapkamer
          default: 21.0
          selector:
            number:
              min: 10
              max: 30
              step: 0.5
              unit_of_measurement: "°C"

    weather_section:
      name: Weersensoren
      description: Configureer de weersensoren
      input:
        weather_sensor:
          name: Weersensor
          selector:
            entity:
              domain: sensor
              device_class: temperature

    tweaks_section:
      name: Tweaks
      description: Stel de tweakers in
      input:
        hysteresis_value:
          name: Hysteresis Waarde
          description: De marge om te voorkomen dat de ventilator te snel schakelt.
          default: 0.5
          selector:
            number:
              min: 0.1
              max: 5.0
              step: 0.1
              unit_of_measurement: "°C"
        rain_threshold_value:
          name: Neerslagdrempel
          description: Minimale hoeveelheid neerslag om de ventilator uit te schakelen.
          default: 0.1
          selector:
            number:
              min: 0.0
              max: 5.0
              step: 0.1
              unit_of_measurement: "mm"
        minimale_schakeltijd:
          name: Minimale Schakeltijd
          description: Minimale tijd tussen schakelingen van de ventilator.
          default: 1.0
          selector:
            number:
              min: 0.1
              max: 60.0
              step: 0.1
              unit_of_measurement: "minuten"

  trigger:
    - platform: state
      entity_id:
        - sensor.thermostaat_woonkamer_binnentemperatuur
        - sensor.sensor_slaapkamer_temperature
        - sensor.sensor_kantoor_temperature
        - sensor.sensor_zolder_temperature

  condition:
    - condition: or
      conditions:
        - condition: numeric_state
          entity_id: sensor.thermostaat_woonkamer_binnentemperatuur
          above: '{{ input.desired_temp_woonkamer | float }}'
        - condition: numeric_state
          entity_id: sensor.sensor_slaapkamer_temperature
          above: '{{ input.desired_temp_slaapkamer | float }}'

  action:
    - choose:
        - conditions:
            - condition: numeric_state
              entity_id: sensor.thermostaat_woonkamer_binnentemperatuur
              above: '{{ input.desired_temp_woonkamer | float }}'
          sequence:
            - service: switch.turn_on
              target:
                entity_id: '{{ input.fan_switch_woonkamer }}'
        - conditions:
            - condition: numeric_state
              entity_id: sensor.sensor_slaapkamer_temperature
              above: '{{ input.desired_temp_slaapkamer | float }}'
          sequence:
            - service: switch.turn_on
              target:
                entity_id: '{{ input.fan_switch_slaapkamer }}'
      default:
        - service: switch.turn_off
          target:
            entity_id:
              - '{{ input.fan_switch_woonkamer }}'
              - '{{ input.fan_switch_slaapkamer }}'
