blueprint:
  name: Ventilatiesysteem met Hysteresis en Tweaks (4 Ventilatoren) - Versie 2.91
  description: >
    Dit script regelt de ventilatie in meerdere kamers op basis van temperatuurmetingen, neerslag en hysteresis. 
    Elke ventilator kan individueel worden ingesteld, met tweaks voor schakeltijd, regenuitschakeling en hysteresis.
    
    **Versie**: 2.91

  domain: automation
  input:
    woonkamer_temperature:
      name: Woonkamer Temperatuur Sensor
      description: Temperatuur sensor in de woonkamer
      selector:
        entity:
          domain: sensor
    slaapkamer_temperature:
      name: Slaapkamer Temperatuur Sensor
      description: Temperatuur sensor in de slaapkamer
      selector:
        entity:
          domain: sensor
    buiten_weather:
      name: Buiten Weer Sensor
      description: Weer sensor voor neerslag
      selector:
        entity:
          domain: sensor
    vakantie_schakelaar:
      name: Vakantie Schakelaar
      description: Schakelaar die vakantie-status aangeeft
      selector:
        entity:
          domain: binary_sensor
    ventilator_1:
      name: Ventilator 1
      description: Eerste ventilator
      selector:
        entity:
          domain: switch
    ventilator_2:
      name: Ventilator 2
      description: Tweede ventilator
      selector:
        entity:
          domain: switch
    ventilator_3:
      name: Ventilator 3
      description: Derde ventilator
      selector:
        entity:
          domain: switch
    ventilator_4:
      name: Ventilator 4
      description: Vierde ventilator
      selector:
        entity:
          domain: switch
    hysteresis:
      name: Hysteresis Waarde
      description: Waarde voor hysteresis om frequent schakelen te voorkomen
      default: 1
      selector:
        number:
          min: 0
          max: 10
          unit_of_measurement: "°C"
    regendrempel:
      name: Regendrempel
      description: Minimale hoeveelheid neerslag om ventilatoren uit te schakelen
      default: 0
      selector:
        number:
          min: 0
          max: 100
          unit_of_measurement: "mm"
    minimale_schakeltijd:
      name: Minimale Schakeltijd
      description: Tijd tussen schakelingen om te voorkomen dat ventilatoren te vaak schakelen
      default: 5
      selector:
        number:
          min: 0
          max: 60
          unit_of_measurement: "min"

trigger:
  - platform: state
    entity_id: !input woonkamer_temperature
  - platform: state
    entity_id: !input slaapkamer_temperature
  - platform: state
    entity_id: !input buiten_weather
  - platform: state
    entity_id: !input vakantie_schakelaar

condition:
  - condition: state
    entity_id: !input vakantie_schakelaar
    state: 'off'
  - condition: numeric_state
    entity_id: !input buiten_weather
    above: !input regendrempel

action:
  - choose:
      - conditions:
          - condition: numeric_state
            entity_id: !input woonkamer_temperature
            above: !input hysteresis
          - condition: numeric_state
            entity_id: !input slaapkamer_temperature
            above: !input hysteresis
        sequence:
          - service: switch.turn_on
            target:
              entity_id: !input ventilator_1
          - service: switch.turn_on
            target:
              entity_id: !input ventilator_2
          - service: switch.turn_on
            target:
              entity_id: !input ventilator_3
          - service: switch.turn_on
            target:
              entity_id: !input ventilator_4
      default:
        - service: switch.turn_off
          target:
            entity_id: !input ventilator_1
        - service: switch.turn_off
          target:
            entity_id: !input ventilator_2
        - service: switch.turn_off
          target:
            entity_id: !input ventilator_3
        - service: switch.turn_off
          target:
            entity_id: !input ventilator_4
