blueprint:
  name: Ventilatiesysteem met Hysteresis en Tweaks (4 Ventilatoren) - Versie 3.03
  description: >
    Dit script regelt de ventilatie in meerdere kamers op basis van de binnentemperatuur, buitentemperatuur, neerslag en hysteresis. Elke ventilator kan individueel worden ingesteld, en er zijn tweaks voor schakeltijd, regenuitschakeling en hysteresis. Een vakantieschakeling is toegevoegd voor wanneer de bewoners op vakantie zijn.

  domain: automation
  input:
    ventilator_section:
      name: Ventilatoren
      icon: mdi:fan
      input:
        fan_switch_woonkamer:
          name: Ventilator Woonkamer
          selector:
            entity:
              domain: switch
        temp_sensor_woonkamer:
          name: Temperatuursensor Woonkamer
          selector:
            entity:
              domain: sensor
              device_class: temperature
        desired_temp_woonkamer:
          name: Gewenste Kamertemperatuur Woonkamer
          default: 21.0
          selector:
            number:
              min: 10
              max: 30
              step: 0.5
              unit_of_measurement: "°C"
        hysteresis:
          name: Hysteresis
          default: 0.5
          selector:
            number:
              min: 0
              max: 5
              step: 0.1
              unit_of_measurement: "°C"
        disable_rain_shutdown_woonkamer:
          name: Regenuitschakeling voor Woonkamer
          description: "Schakel ventilator uit bij regen."
          default: false
          selector:
            boolean: {}
        vacation_mode:
          name: Vakantieschakeling
          description: "Indien aan, zullen de ventilatoren niet draaien."
          default: false
          selector:
            boolean: {}
        weather_sensor:
          name: Weersensor
          selector:
            entity:
              domain: sensor
              device_class: precipitation

  trigger:
    - platform: state
      entity_id:
        - '{{ temp_sensor_woonkamer }}'
        - '{{ weather_sensor }}'

  condition:
    - condition: template
      value_template: "{{ not is_state(vacation_mode, 'on') }}"
    - condition: template
      value_template: "{{ state_attr(weather_sensor, 'precipitation') < 1 or not disable_rain_shutdown_woonkamer }}"

  action:
    - choose:
        - conditions:
            - condition: template
              value_template: "{{ states(temp_sensor_woonkamer) | float < desired_temp_woonkamer - hysteresis }}"
          sequence:
            - service: switch.turn_on
              target:
                entity_id: '{{ fan_switch_woonkamer }}'
        - conditions:
            - condition: template
              value_template: "{{ states(temp_sensor_woonkamer) | float > desired_temp_woonkamer + hysteresis }}"
          sequence:
            - service: switch.turn_off
              target:
                entity_id: '{{ fan_switch_woonkamer }}'

    - event: ventilation_event
      event_data:
        thermostat: '{{ temp_sensor_woonkamer }}'
        mode: '{{ states(fan_switch_woonkamer) }}'
        target_temperature: '{{ desired_temp_woonkamer }}'
        is_vacation_mode: '{{ is_state(vacation_mode, 'on') }}'
        precipitation: '{{ state_attr(weather_sensor, 'precipitation') }}'
