blueprint:
  name: "GebouwBeheerVentilatie versie 13.1"
  description: >
    Blueprint voor het beheren van ventilatoren en afzuiginstallatie op basis van temperatuur, vochtigheid, en weersomstandigheden. 
    Deze versie bevat instellingen voor 4 ruimtes: Woonkamer, Master Bedroom, Kantoorruimte, Zolder.
    De ventilatoren kunnen individueel worden uitgeschakeld bij regen en er zijn seizoensmodi gebaseerd op buitentemperatuur.

    ## Ruimtes
    - Woonkamer (Ventilator, Temperatuursensor, Regenschakelaar)
    - Master Bedroom (Ventilator, Temperatuursensor, Luchtvochtigheidssensor, Regenschakelaar)
    - Kantoorruimte (Ventilator, Temperatuursensor, Luchtvochtigheidssensor, Regenschakelaar)
    - Zolder (Ventilator, Temperatuursensor, Luchtvochtigheidssensor, Regenschakelaar)

    ## Vakantiemodus
    De ventilatoren en afzuiginstallatie kunnen uitgeschakeld worden als de vakantiemodus actief is.
    
  domain: automation
  input:
    weather_sensor:
      name: Weersensor
      description: Selecteer de weersensor die wordt gebruikt voor temperatuur en neerslag (bijv. Buienradar).
      selector:
        entity:
          domain: weather

    regendrempel:
      name: Regendrempelwaarde
      description: Stel de drempelwaarde in voor regen waarbij ventilatoren worden uitgeschakeld.
      selector:
        number:
          min: 0
          max: 10
          step: 0.1
          unit_of_measurement: "mm"
      default: 0.2
    
    woonkamer_fan:
      name: Ventilator Woonkamer
      description: Selecteer de ventilator voor de Woonkamer.
      selector:
        entity:
          domain: switch

    woonkamer_temp_sensor:
      name: Temperatuursensor Woonkamer
      description: Selecteer de temperatuursensor voor de Woonkamer.
      selector:
        entity:
          domain: sensor
          device_class: temperature

    woonkamer_regen_sensor:
      name: Regenschakelaar Woonkamer
      description: Selecteer de regensensor voor de Woonkamer.
      selector:
        entity:
          domain: binary_sensor

    master_bedroom_fan:
      name: Ventilator Master Bedroom
      description: Selecteer de ventilator voor de Master Bedroom.
      selector:
        entity:
          domain: switch

    master_bedroom_temp_sensor:
      name: Temperatuursensor Master Bedroom
      description: Selecteer de temperatuursensor voor de Master Bedroom.
      selector:
        entity:
          domain: sensor
          device_class: temperature

    master_bedroom_humidity_sensor:
      name: Luchtvochtigheidssensor Master Bedroom (Optioneel)
      description: Selecteer de luchtvochtigheidssensor voor de Master Bedroom.
      selector:
        entity:
          domain: sensor
          device_class: humidity
      optional: true

    master_bedroom_regen_sensor:
      name: Regenschakelaar Master Bedroom
      description: Selecteer de regensensor voor de Master Bedroom.
      selector:
        entity:
          domain: binary_sensor

    kantoor_fan:
      name: Ventilator Kantoorruimte
      description: Selecteer de ventilator voor de Kantoorruimte.
      selector:
        entity:
          domain: switch

    kantoor_temp_sensor:
      name: Temperatuursensor Kantoorruimte
      description: Selecteer de temperatuursensor voor de Kantoorruimte.
      selector:
        entity:
          domain: sensor
          device_class: temperature

    kantoor_humidity_sensor:
      name: Luchtvochtigheidssensor Kantoorruimte (Optioneel)
      description: Selecteer de luchtvochtigheidssensor voor de Kantoorruimte.
      selector:
        entity:
          domain: sensor
          device_class: humidity
      optional: true

    kantoor_regen_sensor:
      name: Regenschakelaar Kantoorruimte
      description: Selecteer de regensensor voor de Kantoorruimte.
      selector:
        entity:
          domain: binary_sensor

    zolder_fan:
      name: Ventilator Zolder
      description: Selecteer de ventilator voor de Zolder.
      selector:
        entity:
          domain: switch

    zolder_temp_sensor:
      name: Temperatuursensor Zolder
      description: Selecteer de temperatuursensor voor de Zolder.
      selector:
        entity:
          domain: sensor
          device_class: temperature

    zolder_humidity_sensor:
      name: Luchtvochtigheidssensor Zolder (Optioneel)
      description: Selecteer de luchtvochtigheidssensor voor de Zolder.
      selector:
        entity:
          domain: sensor
          device_class: humidity
      optional: true

    zolder_regen_sensor:
      name: Regenschakelaar Zolder
      description: Selecteer de regensensor voor de Zolder.
      selector:
        entity:
          domain: binary_sensor

    ventilator_afzuiging:
      name: Afzuiginstallatie
      description: Selecteer de afzuiginstallatie (Optioneel).
      selector:
        entity:
          domain: switch
      optional: true

    vakantie_sensor:
      name: Vakantiesensor
      description: Selecteer de sensor die bepaalt of de woning in vakantiemodus is.
      selector:
        entity:
          domain: binary_sensor

    seizoensmodus_winter_temp:
      name: Seizoensmodus Wintertemperatuur
      description: Buitentemperatuur waarbij het systeem in wintermodus gaat.
      selector:
        number:
          min: -10
          max: 15
          step: 0.5
          unit_of_measurement: "°C"
      default: 10

    seizoensmodus_zomer_temp:
      name: Seizoensmodus Zomertemperatuur
      description: Buitentemperatuur waarbij het systeem in zomerstand gaat.
      selector:
        number:
          min: 15
          max: 35
          step: 0.5
          unit_of_measurement: "°C"
      default: 25

trigger:
  - platform: state
    entity_id: !input woonkamer_temp_sensor
  - platform: state
    entity_id: !input vakantie_sensor

variables:
  weather_entity: !input weather_sensor
  woonkamer_fan_entity: !input woonkamer_fan
  master_bedroom_fan_entity: !input master_bedroom_fan
  kantoor_fan_entity: !input kantoor_fan
  zolder_fan_entity: !input zolder_fan
  ventilator_afzuiging_entity: !input ventilator_afzuiging
  vakantie_sensor_entity: !input vakantie_sensor
  regendrempel_value: !input regendrempel
  seizoensmodus_winter_temp: !input seizoensmodus_winter_temp
  seizoensmodus_zomer_temp: !input seizoensmodus_zomer_temp

action:
  - choose:
      - conditions:
          - condition: template
            value_template: "{{ is_state(vakantie_sensor_entity, 'on') }}"
        sequence:
          - choose:
              - conditions:
                  - condition: template
                    value_template: "{{ vakantie_ventilator }}"
                sequence:
                  - service: switch.turn_off
                    target:
                      entity_id: "{{ woonkamer_fan_entity }}"
              - conditions:
                  - condition: template
                    value_template: "{{ vakantie_afzuiging }}"
                sequence:
                  - service: switch.turn_off
                    target:
                      entity_id: "{{ ventilator_afzuiging_entity }}"
