blueprint:
  name: GebouwBeheerVentilatie versie 13.2
  description: >
    Beheer van ventilatoren en afzuiging per ruimte met weersensor integratie. 
    Deze automatisering houdt rekening met temperatuur, vochtigheid, regen, 
    en seizoensmodi. Optionele instellingen voor de afzuiginstallatie en vakantiemodus.
  domain: automation
  input:
    weather_sensor:
      name: Weersensor
      description: Selecteer de weersensor die gebruikt moet worden voor de temperatuur- en neerslaggegevens.
      selector:
        entity:
          domain: weather
    woonkamer_fan:
      name: Ventilator Woonkamer
      description: Selecteer de ventilator voor de Woonkamer
      selector:
        entity:
          domain: switch
    woonkamer_temp_sensor:
      name: Temperatuursensor Woonkamer
      description: Selecteer de temperatuursensor voor de Woonkamer
      selector:
        entity:
          domain: sensor
          device_class: temperature
    woonkamer_regen_sensor:
      name: Regenschakelaar Woonkamer
      description: Selecteer de regenschakelaar voor de Woonkamer. Deze schakelt de ventilator uit bij regen.
      selector:
        entity:
          domain: binary_sensor
          device_class: moisture
    master_bedroom_fan:
      name: Ventilator Master Bedroom
      description: Selecteer de ventilator voor de Master Bedroom
      selector:
        entity:
          domain: switch
    master_bedroom_temp_sensor:
      name: Temperatuursensor Master Bedroom
      description: Selecteer de temperatuursensor voor de Master Bedroom
      selector:
        entity:
          domain: sensor
          device_class: temperature
    master_bedroom_humidity_sensor:
      name: Luchtvochtigheidssensor Master Bedroom (Optioneel)
      description: Selecteer de luchtvochtigheidssensor voor de Master Bedroom (optioneel)
      selector:
        entity:
          domain: sensor
          device_class: humidity
      default: null
    kantoor_fan:
      name: Ventilator Kantoorruimte
      description: Selecteer de ventilator voor de Kantoorruimte
      selector:
        entity:
          domain: switch
    kantoor_temp_sensor:
      name: Temperatuursensor Kantoorruimte
      description: Selecteer de temperatuursensor voor de Kantoorruimte
      selector:
        entity:
          domain: sensor
          device_class: temperature
    kantoor_humidity_sensor:
      name: Luchtvochtigheidssensor Kantoorruimte (Optioneel)
      description: Selecteer de luchtvochtigheidssensor voor de Kantoorruimte (optioneel)
      selector:
        entity:
          domain: sensor
          device_class: humidity
      default: null
    zolder_fan:
      name: Ventilator Zolder
      description: Selecteer de ventilator voor de Zolder
      selector:
        entity:
          domain: switch
    zolder_temp_sensor:
      name: Temperatuursensor Zolder
      description: Selecteer de temperatuursensor voor de Zolder
      selector:
        entity:
          domain: sensor
          device_class: temperature
    zolder_humidity_sensor:
      name: Luchtvochtigheidssensor Zolder (Optioneel)
      description: Selecteer de luchtvochtigheidssensor voor de Zolder (optioneel)
      selector:
        entity:
          domain: sensor
          device_class: humidity
      default: null
    ventilator_afzuiging:
      name: Afzuiginstallatie (Optioneel)
      description: Selecteer de afzuiginstallatie (optioneel)
      selector:
        entity:
          domain: switch
      default: null
    vakantie_sensor:
      name: Vakantiesensor
      description: Selecteer de sensor die bepaalt of de woning in vakantiemodus is
      selector:
        entity:
          domain: binary_sensor
    regendrempel:
      name: Drempel voor regenwaarde
      description: >
        Stel de drempel in voor de neerslagwaarde waarop de ventilatoren uitschakelen. 
        Advies: Motregen begint rond 0.2 mm, miezeren rond 0.5 mm en harde regen rond 1.0 mm.
      selector:
        number:
          min: 0
          max: 5
          step: 0.1
          unit_of_measurement: mm

variables:
  weather_entity: !input weather_sensor
  woonkamer_fan_entity: !input woonkamer_fan
  master_bedroom_fan_entity: !input master_bedroom_fan
  kantoor_fan_entity: !input kantoor_fan
  zolder_fan_entity: !input zolder_fan
  ventilator_afzuiging_entity: !input ventilator_afzuiging
  vakantie_sensor_entity: !input vakantie_sensor
  regendrempel_value: !input regendrempel
  seizoensmodus_winter_temp: 10
  seizoensmodus_zomer_temp: 25

trigger:
  - platform: state
    entity_id: !input woonkamer_temp_sensor
  - platform: state
    entity_id: !input vakantie_sensor

condition: []

action:
  - choose:
      - conditions:
          - condition: template
            value_template: "{{ is_state(vakantie_sensor_entity, 'on') }}"
        sequence:
          - choose:
              - conditions:
                  - condition: template
                    value_template: "{{ vakantie_ventilator }}"
                sequence:
                  - service: switch.turn_off
                    target:
                      entity_id: "{{ woonkamer_fan_entity }}"
              - conditions:
                  - condition: template
                    value_template: "{{ vakantie_afzuiging }}"
                sequence:
                  - service: switch.turn_off
                    target:
                      entity_id: "{{ ventilator_afzuiging_entity }}"
  default: []
