blueprint:
  name: Ventilatie- en Afzuigsysteem Automatisering
  description: |
    Automatisering voor het beheren van ventilatoren, afzuiging, en regensensoren per ruimte. 
    Elke ruimte kan ook optioneel een luchtvochtigheidssensor hebben.
  domain: automation
  homeassistant:
    min_version: "2024.9.0"
  input:

    # Woonkamer
    woonkamer_section:
      name: Woonkamer
      description: Instellingen voor de woonkamer
      selector:
        entity:
          domain: switch
      input:
        woonkamer_fan:
          name: Ventilator Woonkamer
          description: Selecteer de ventilator voor de woonkamer
          selector:
            entity:
              domain: switch
        woonkamer_temp_sensor:
          name: Temperatuursensor Woonkamer
          description: Selecteer de temperatuursensor voor de woonkamer
          selector:
            entity:
              domain: sensor
              device_class: temperature
        woonkamer_regen_sensor:
          name: Regenschakelaar Woonkamer
          description: Selecteer de regensensor voor de woonkamer
          selector:
            entity:
              domain: binary_sensor

    # Master Bedroom
    master_bedroom_section:
      name: Master Bedroom
      description: Instellingen voor de Master Bedroom
      selector:
        entity:
          domain: switch
      input:
        master_bedroom_fan:
          name: Ventilator Master Bedroom
          description: Selecteer de ventilator voor de Master Bedroom
          selector:
            entity:
              domain: switch
        master_bedroom_temp_sensor:
          name: Temperatuursensor Master Bedroom
          description: Selecteer de temperatuursensor voor de Master Bedroom
          selector:
            entity:
              domain: sensor
              device_class: temperature
        master_bedroom_humidity_sensor:
          name: Luchtvochtigheidssensor Master Bedroom (Optioneel)
          description: Selecteer de luchtvochtigheidssensor voor de Master Bedroom
          selector:
            entity:
              domain: sensor
              device_class: humidity
        master_bedroom_regen_sensor:
          name: Regenschakelaar Master Bedroom
          description: Selecteer de regensensor voor de Master Bedroom
          selector:
            entity:
              domain: binary_sensor

    # Kantoorruimte
    kantoorruimte_section:
      name: Kantoorruimte
      description: Instellingen voor de kantoorruimte
      selector:
        entity:
          domain: switch
      input:
        kantoor_fan:
          name: Ventilator Kantoorruimte
          description: Selecteer de ventilator voor de Kantoorruimte
          selector:
            entity:
              domain: switch
        kantoor_temp_sensor:
          name: Temperatuursensor Kantoorruimte
          description: Selecteer de temperatuursensor voor de Kantoorruimte
          selector:
            entity:
              domain: sensor
              device_class: temperature
        kantoor_humidity_sensor:
          name: Luchtvochtigheidssensor Kantoorruimte (Optioneel)
          description: Selecteer de luchtvochtigheidssensor voor de Kantoorruimte
          selector:
            entity:
              domain: sensor
              device_class: humidity
        kantoor_regen_sensor:
          name: Regenschakelaar Kantoorruimte
          description: Selecteer de regensensor voor de Kantoorruimte
          selector:
            entity:
              domain: binary_sensor

    # Zolder
    zolder_section:
      name: Zolder
      description: Instellingen voor de zolder
      selector:
        entity:
          domain: switch
      input:
        zolder_fan:
          name: Ventilator Zolder
          description: Selecteer de ventilator voor de Zolder
          selector:
            entity:
              domain: switch
        zolder_temp_sensor:
          name: Temperatuursensor Zolder
          description: Selecteer de temperatuursensor voor de Zolder
          selector:
            entity:
              domain: sensor
              device_class: temperature
        zolder_humidity_sensor:
          name: Luchtvochtigheidssensor Zolder (Optioneel)
          description: Selecteer de luchtvochtigheidssensor voor de Zolder
          selector:
            entity:
              domain: sensor
              device_class: humidity
        zolder_regen_sensor:
          name: Regenschakelaar Zolder
          description: Selecteer de regensensor voor de Zolder
          selector:
            entity:
              domain: binary_sensor

    # Afzuiginstallatie
    ventilator_afzuiging:
      name: Afzuiginstallatie
      description: Selecteer de afzuiginstallatie (optioneel)
      selector:
        entity:
          domain: switch

    # Overwerktijd
    overwerktijd:
      name: Overwerktijd
      description: Stel in hoelang de overwerkmodus actief blijft (standaard 30 minuten)
      selector:
        number:
          min: 5
          max: 120
          step: 5
          unit_of_measurement: minutes
      default: 30

    # Vakantiemodus
    vakantie_sensor:
      name: Vakantiesensor
      description: Selecteer de helper die bepaalt of de woning in vakantiemodus is
      selector:
        entity:
          domain: input_boolean

    vakantie_ventilator:
      name: Ventilatoren uitschakelen in vakantiemodus?
      description: Schakel ventilatoren uit als de vakantiemodus actief is
      selector:
        boolean:
      default: true

    vakantie_afzuiging:
      name: Afzuiginstallatie uitschakelen in vakantiemodus?
      description: Schakel afzuiginstallatie uit als de vakantiemodus actief is
      selector:
        boolean:
      default: true

    # Seizoensmodus instellingen
    seizoensmodus_zomer_temp:
      name: Zomertemperatuurgrens
      description: Bepaal de binnentemperatuurgrens waarbij de zomerseizoenmodus wordt ingeschakeld
      selector:
        number:
          min: 10
          max: 30
          step: 0.5
          unit_of_measurement: °C
      default: 15

    seizoensmodus_winter_temp:
      name: Wintertemperatuurgrens
      description: Bepaal de buitentemperatuur waarbij de winterseizoenmodus wordt ingeschakeld
      selector:
        number:
          min: -10
          max: 10
          step: 0.5
          unit_of_measurement: °C
      default: 5

trigger:
  - platform: state
    entity_id: !input woonkamer_temp_sensor
  - platform: state
    entity_id: !input vakantie_sensor

condition: []
action:
  - choose:
      - conditions:
          - condition: template
            value_template: "{{ is_state(!input vakantie_sensor, 'on') }}"
        sequence:
          - choose:
              - conditions:
                  - condition: template
                    value_template: "{{ !input vakantie_ventilator }}"
                sequence:
                  - service: switch.turn_off
                    target:
                      entity_id: !input woonkamer_fan
              - conditions:
                  - condition: template
                    value_template: "{{ !input vakantie_afzuiging }}"
                sequence:
                  - service: switch.turn_off
                    target:
                      entity_id: !input ventilator_afzuiging
      - conditions:
          - condition: template
            value_template: "{{ states('sensor.buitentemperatuur') | float > !input seizoensmodus_winter_temp }}"
        sequence:
          - service: switch.turn_on
            target:
              entity_id: !input ventilator_afzuiging
      - conditions:
          - condition: template
            value_template: "{{ states('sensor.binnentemperatuur') | float < !input seizoensmodus_zomer_temp }}"
        sequence:
          - service: switch.turn_on
            target:
              entity_id: !input woonkamer_fan

mode: single
