blueprint:
  name: Ventilatie- en Afzuigsysteem Automatisering
  description: |
    Automatisering voor het beheren van ventilatoren, afzuiging, en regensensoren per ruimte. 
    Elke ruimte kan optioneel een luchtvochtigheidssensor hebben, en er is een instelbare drempelwaarde voor regen.
    
    Advies voor regendrempels:
      - Motregen: ongeveer 0.2 mm/uur
      - Miezeren: ongeveer 0.5 mm/uur
      - Harde regen: 2 mm/uur of meer
    Aanbevolen drempelwaarde voor uitschakeling: 0.3 mm/uur (net onder motregen).
    
  domain: automation
  homeassistant:
    min_version: "2024.9.0"
  input:
    # Woonkamer
    woonkamer_fan:
      name: Ventilator Woonkamer
      description: Selecteer de ventilator voor de woonkamer
      selector:
        entity:
          domain: switch
    woonkamer_temp_sensor:
      name: Temperatuursensor Woonkamer
      description: Selecteer de temperatuursensor voor de woonkamer
      selector:
        entity:
          domain: sensor
          device_class: temperature
    woonkamer_regen_sensor:
      name: Regenschakelaar Woonkamer
      description: Selecteer of deze ventilator moet worden uitgeschakeld bij regen
      selector:
        boolean:
      default: false

    # Master Bedroom
    master_bedroom_fan:
      name: Ventilator Master Bedroom
      description: Selecteer de ventilator voor de Master Bedroom
      selector:
        entity:
          domain: switch
    master_bedroom_temp_sensor:
      name: Temperatuursensor Master Bedroom
      description: Selecteer de temperatuursensor voor de Master Bedroom
      selector:
        entity:
          domain: sensor
          device_class: temperature
    master_bedroom_humidity_sensor:
      name: Luchtvochtigheidssensor Master Bedroom (Optioneel)
      description: Selecteer de luchtvochtigheidssensor voor de Master Bedroom
      selector:
        entity:
          domain: sensor
          device_class: humidity
    master_bedroom_regen_sensor:
      name: Regenschakelaar Master Bedroom
      description: Selecteer of deze ventilator moet worden uitgeschakeld bij regen
      selector:
        boolean:
      default: false

    # Kantoorruimte
    kantoor_fan:
      name: Ventilator Kantoorruimte
      description: Selecteer de ventilator voor de Kantoorruimte
      selector:
        entity:
          domain: switch
    kantoor_temp_sensor:
      name: Temperatuursensor Kantoorruimte
      description: Selecteer de temperatuursensor voor de Kantoorruimte
      selector:
        entity:
          domain: sensor
          device_class: temperature
    kantoor_humidity_sensor:
      name: Luchtvochtigheidssensor Kantoorruimte (Optioneel)
      description: Selecteer de luchtvochtigheidssensor voor de Kantoorruimte
      selector:
        entity:
          domain: sensor
          device_class: humidity
    kantoor_regen_sensor:
      name: Regenschakelaar Kantoorruimte
      description: Selecteer of deze ventilator moet worden uitgeschakeld bij regen
      selector:
        boolean:
      default: false

    # Zolder
    zolder_fan:
      name: Ventilator Zolder
      description: Selecteer de ventilator voor de Zolder
      selector:
        entity:
          domain: switch
    zolder_temp_sensor:
      name: Temperatuursensor Zolder
      description: Selecteer de temperatuursensor voor de Zolder
      selector:
        entity:
          domain: sensor
          device_class: temperature
    zolder_humidity_sensor:
      name: Luchtvochtigheidssensor Zolder (Optioneel)
      description: Selecteer de luchtvochtigheidssensor voor de Zolder
      selector:
        entity:
          domain: sensor
          device_class: humidity
    zolder_regen_sensor:
      name: Regenschakelaar Zolder
      description: Selecteer of deze ventilator moet worden uitgeschakeld bij regen
      selector:
        boolean:
      default: false

    # Afzuiginstallatie
    ventilator_afzuiging:
      name: Afzuiginstallatie
      description: Selecteer de afzuiginstallatie (optioneel)
      selector:
        entity:
          domain: switch

    # Overwerktijd
    overwerktijd:
      name: Overwerktijd
      description: Stel in hoelang de overwerkmodus actief blijft (standaard 30 minuten)
      selector:
        number:
          min: 5
          max: 120
          step: 5
          unit_of_measurement: minutes
      default: 30

    # Vakantiemodus
    vakantie_sensor:
      name: Vakantiesensor
      description: Selecteer de helper die bepaalt of de woning in vakantiemodus is
      selector:
        entity:
          domain: input_boolean

    vakantie_ventilator:
      name: Ventilatoren uitschakelen in vakantiemodus?
      description: Schakel ventilatoren uit als de vakantiemodus actief is
      selector:
        boolean:
      default: true

    vakantie_afzuiging:
      name: Afzuiginstallatie uitschakelen in vakantiemodus?
      description: Schakel afzuiginstallatie uit als de vakantiemodus actief is
      selector:
        boolean:
      default: true

    # Regendrempel
    regendrempel:
      name: Regendrempel
      description: Bepaal de drempelwaarde voor regen in mm/uur waarbij ventilatoren worden uitgeschakeld.
      selector:
        number:
          min: 0
          max: 10
          step: 0.1
          unit_of_measurement: mm/uur
      default: 0.3

trigger:
  - platform: state
    entity_id: !input woonkamer_temp_sensor
  - platform: state
    entity_id: !input vakantie_sensor

condition: []
action:
  - choose:
      - conditions:
          - condition: template
            value_template: "{{ is_state(!input vakantie_sensor, 'on') }}"
        sequence:
          - choose:
              - conditions:
                  - condition: template
                    value_template: "{{ !input vakantie_ventilator }}"
                sequence:
                  - service: switch.turn_off
                    target:
                      entity_id: !input woonkamer_fan
              - conditions:
                  - condition: template
                    value_template: "{{ !input vakantie_afzuiging }}"
                sequence:
                  - service: switch.turn_off
                    target:
                      entity_id: !input ventilator_afzuiging
      - conditions:
          - condition: template
            value_template: "{{ states('sensor.buitentemperatuur') | float > !input seizoensmodus_winter_temp }}"
        sequence:
          - service: switch.turn_on
            target:
              entity_id: !input ventilator_afzuiging
      - conditions:
          - condition: template
            value_template: "{{ states('sensor.binnentemperatuur') | float < !input seizoensmodus_zomer_temp }}"
        sequence:
          - service: switch.turn_on
            target:
              entity_id: !input woonkamer_fan
      - conditions:
          - condition: template
            value_template: "{{ states('sensor.buienradar') | float > !input regendrempel }}"
        sequence:
          - choose:
              - conditions:
                  - condition: template
                    value_template: "{{ !input woonkamer_regen_sensor }}"
                sequence:
                  - service: switch.turn_off
                    target:
                      entity_id: !input woonkamer_fan
              - conditions:
                  - condition: template
                    value_template: "{{ !input master_bedroom_regen_sensor }}"
                sequence:
                  - service: switch.turn_off
                    target:
                      entity_id: !input master_bedroom_fan
              - conditions:
                  - condition: template
                    value_template: "{{ !input kantoor_regen_sensor }}"
                sequence:
                  - service: switch.turn_off
                    target:
                      entity_id: !input kantoor_fan
              - conditions:
                  - condition: template
                    value_template: "{{ !input zolder_regen_sensor }}"
                sequence:
                  - service: switch.turn_off
                    target:
                      entity_id: !input zolder_fan

mode: single
