# Template sensoren om de laatste bekende waarden voor binnen- en buitentemperatuur op te slaan
- platform: template
  sensors:
    last_known_binnentemperatuur:
      friendly_name: "Laatste bekende binnentemperatuur"
      unit_of_measurement: "°C"
      value_template: >
        {% if states('sensor.sensor_slaapkamer_temperature') not in ['unknown', 'unavailable'] %}
          {{ states('sensor.sensor_slaapkamer_temperature') }}
        {% else %}
          {{ states('sensor.last_known_binnentemperatuur') | float(21.0) }}
        {% endif %}

    last_known_buiten_temp:
      friendly_name: "Laatste bekende buitentemperatuur"
      unit_of_measurement: "°C"
      value_template: >
        {% if state_attr('weather.buienradar', 'temperature') is not none %}
          {{ state_attr('weather.buienradar', 'temperature') }}
        {% else %}
          {{ states('sensor.last_known_buiten_temp') | float(15.0) }}
        {% endif %}
