blueprint:
  name: "Ventilatiesysteem Master Bedroom"
  description: >
    Dit systeem automatiseert de ventilator in de Master Bedroom op basis van de binnentemperatuur, buitentemperatuur en weersomstandigheden zoals regen. 
    Het bevat ook een overwerktimer en ondersteunt handmatige bediening via een switch.
  
  domain: automation
  input:
    fan_switch:
      name: Ventilator Switch
      description: De schakelaar voor de ventilator.
      selector:
        entity:
          domain: switch

    temp_sensor:
      name: Temperatuursensor Binnen
      description: De temperatuursensor voor de kamer.
      selector:
        entity:
          domain: sensor
          device_class: temperature

    weather_sensor:
      name: Weersensor (bijv. Buienradar)
      description: De sensor die de buitentemperatuur en neerslag doorgeeft.
      selector:
        entity:
          domain: weather

    desired_temp:
      name: Gewenste Kamertemperatuur
      description: De temperatuur die je wilt behouden in de Master Bedroom.
      default: 22
      selector:
        number:
          min: 16
          max: 30
          unit_of_measurement: "°C"
          mode: slider

    rain_threshold:
      name: Regendrempel
      description: De hoeveelheid regen (in mm) waarbij de ventilator uitgeschakeld moet worden. Standaardwaarde is motregen (0.1 mm).
      default: 0.1
      selector:
        number:
          min: 0
          max: 10
          unit_of_measurement: "mm"
          mode: slider

    overwork_duration:
      name: Overwerktimer
      description: Hoe lang de ventilator handmatig aan mag blijven voordat de automatisering het weer overneemt.
      default: 30
      selector:
        number:
          min: 1
          max: 120
          unit_of_measurement: "min"
          mode: slider

trigger:
  - platform: state
    entity_id: !input fan_switch
    to: 'on'
    for:
      minutes: !input overwork_duration

condition:
  - condition: template
    value_template: "{{ states('sensor.' ~ weather_sensor) != 'unavailable' }}"

action:
  - choose:
      - conditions:
          - condition: numeric_state
            entity_id: !input temp_sensor
            above: !input desired_temp
        sequence:
          - service: switch.turn_on
            target:
              entity_id: !input fan_switch
      - conditions:
          - condition: numeric_state
            entity_id: !input weather_sensor
            attribute: precipitation
            above: !input rain_threshold
        sequence:
          - service: switch.turn_off
            target:
              entity_id: !input fan_switch
    default: []
    
mode: restart
