blueprint:
  name: Ventilatiesysteem met Hysteresis en Verbeteringen (4 Ventilatoren)
  description: >
    Automatisch ventilatiesysteem met hysteresis en controle op buitentemperatuur.
    Ventilatoren worden ingeschakeld wanneer de kamertemperatuur boven de gewenste waarde komt,
    en uitgeschakeld op basis van kamertemperatuur én buitentemperatuur.

  domain: automation
  input:
    fan_switch_woonkamer:
      name: Ventilator Woonkamer Schakelaar
      description: "De schakelaar voor de ventilator in de woonkamer."
      selector:
        entity:
          domain: switch
    temp_sensor_woonkamer:
      name: Temperatuursensor Woonkamer
      description: "De temperatuursensor voor de woonkamer."
      selector:
        entity:
          domain: sensor
          device_class: temperature
    desired_temp_woonkamer:
      name: Gewenste Temperatuur Woonkamer
      default: 21
      selector:
        number:
          min: 10
          max: 30
          step: 0.5
          unit_of_measurement: "°C"
          mode: slider
    disable_rain_shutdown_woonkamer:
      name: Uitschakelen bij Regen Woonkamer
      description: "Schakel de ventilator uit bij regen in de woonkamer."
      default: false
      selector:
        boolean: {}

    fan_switch_slaapkamer:
      name: Ventilator Slaapkamer Schakelaar
      description: "De schakelaar voor de ventilator in de slaapkamer."
      selector:
        entity:
          domain: switch
    temp_sensor_slaapkamer:
      name: Temperatuursensor Slaapkamer
      description: "De temperatuursensor voor de slaapkamer."
      selector:
        entity:
          domain: sensor
          device_class: temperature
    desired_temp_slaapkamer:
      name: Gewenste Temperatuur Slaapkamer
      default: 21
      selector:
        number:
          min: 10
          max: 30
          step: 0.5
          unit_of_measurement: "°C"
          mode: slider
    disable_rain_shutdown_slaapkamer:
      name: Uitschakelen bij Regen Slaapkamer
      description: "Schakel de ventilator uit bij regen in de slaapkamer."
      default: false
      selector:
        boolean: {}

    fan_switch_kantoor:
      name: Ventilator Kantoor Schakelaar
      description: "De schakelaar voor de ventilator in het kantoor."
      selector:
        entity:
          domain: switch
    temp_sensor_kantoor:
      name: Temperatuursensor Kantoor
      description: "De temperatuursensor voor het kantoor."
      selector:
        entity:
          domain: sensor
          device_class: temperature
    desired_temp_kantoor:
      name: Gewenste Temperatuur Kantoor
      default: 21
      selector:
        number:
          min: 10
          max: 30
          step: 0.5
          unit_of_measurement: "°C"
          mode: slider
    disable_rain_shutdown_kantoor:
      name: Uitschakelen bij Regen Kantoor
      description: "Schakel de ventilator uit bij regen in het kantoor."
      default: false
      selector:
        boolean: {}

    fan_switch_zolder:
      name: Ventilator Zolder Schakelaar
      description: "De schakelaar voor de ventilator op zolder."
      selector:
        entity:
          domain: switch
    temp_sensor_zolder:
      name: Temperatuursensor Zolder
      description: "De temperatuursensor voor de zolder."
      selector:
        entity:
          domain: sensor
          device_class: temperature
    desired_temp_zolder:
      name: Gewenste Temperatuur Zolder
      default: 21
      selector:
        number:
          min: 10
          max: 30
          step: 0.5
          unit_of_measurement: "°C"
          mode: slider
    disable_rain_shutdown_zolder:
      name: Uitschakelen bij Regen Zolder
      description: "Schakel de ventilator uit bij regen op zolder."
      default: false
      selector:
        boolean: {}

    weather_sensor:
      name: Weersensor
      description: "De weersensor die de buitentemperatuur en neerslag meet."
      selector:
        entity:
          domain: weather
    hysteresis:
      name: Hysteresis
      default: 0.5
      selector:
        number:
          min: 0.1
          max: 5.0
          step: 0.1
          unit_of_measurement: "°C"
          mode: slider
    rain_threshold:
      name: Neerslagdrempel
      default: 0.1
      selector:
        number:
          min: 0
          max: 10
          step: 0.1
          unit_of_measurement: "mm"

variables:
  # Definieer de binnentemperaturen en de gewenste waarden
  buiten_temp: "{{ state_attr('weather.buienradar', 'temperature') | float(15) }}"
  neerslag: "{{ state_attr('weather.buienradar', 'precipitation') | float(0) }}"
  binnentemperatuur_woonkamer: "{{ states('sensor.thermostaat_woonkamer_binnentemperatuur') | float(21) }}"
  binnentemperatuur_slaapkamer: "{{ states('sensor.sensor_slaapkamer_temperature') | float(21) }}"
  binnentemperatuur_kantoor: "{{ states('sensor.thermostaat_woonkamer_binnentemperatuur') | float(21) }}"
  binnentemperatuur_zolder: "{{ states('sensor.sensor_slaapkamer_temperature') | float(21) }}"

trigger:
  - platform: time_pattern
    minutes: "/5"
  - platform: state
    entity_id: 
      - sensor.thermostaat_woonkamer_binnentemperatuur
      - sensor.sensor_slaapkamer_temperature
      - sensor.thermostaat_woonkamer_binnentemperatuur
      - sensor.sensor_slaapkamer_temperature
      - weather.buienradar

action:
  - choose:
      # Woonkamer ventilator uitschakelen
      - conditions:
          - condition: template
            value_template: "{{ binnentemperatuur_woonkamer <= desired_temp_woonkamer - hysteresis }}"
          - condition: template
            value_template: "{{ buiten_temp >= binnentemperatuur_woonkamer }}"
        sequence:
          - service: switch.turn_off
            target:
              entity_id: !input 'fan_switch_woonkamer'
          - service: system_log.write
            data:
              message: "Ventilator Woonkamer uitgeschakeld vanwege temperatuurverschil."

      # Slaapkamer ventilator uitschakelen
      - conditions:
          - condition: template
            value_template: "{{ binnentemperatuur_slaapkamer <= desired_temp_slaapkamer - hysteresis }}"
          - condition: template
            value_template: "{{ buiten_temp >= binnentemperatuur_slaapkamer }}"
        sequence:
          - service: switch.turn_off
            target:
              entity_id: !input 'fan_switch_slaapkamer'
          - service: system_log.write
            data:
              message: "Ventilator Slaapkamer uitgeschakeld vanwege temperatuurverschil."

      # Kantoor ventilator uitschakelen
      - conditions:
          - condition: template
            value_template: "{{ binnentemperatuur_kantoor <= desired_temp_kantoor - hysteresis }}"
          - condition: template
            value_template: "{{ buiten_temp >= binnentemperatuur_kantoor }}"
        sequence:
          - service: switch.turn_off
            target:
              entity_id: !input 'fan_switch_kantoor'
          - service: system_log.write
            data:
              message: "Ventilator Kantoor uitgeschakeld vanwege temperatuurverschil."

      # Zolder ventilator uitschakelen
      - conditions:
          - condition: template
            value_template: "{{ binnentemperatuur_zolder <= desired_temp_zolder - hysteresis }}"
          - condition: template
            value_template: "{{ buiten_temp >= binnentemperatuur_zolder }}"
        sequence:
          - service: switch.turn_off
            target:
              entity_id: !input 'fan_switch_zolder'
          - service: system_log.write
            data:
              message: "Ventilator Zolder uitgeschakeld vanwege temperatuurverschil."
