blueprint:
  name: Lamp Timer Uitschakeling
  description: "Deze blueprint houdt de status van een lamp bij en schakelt deze uit na een ingestelde tijd wanneer de lamp wordt aangezet."
  domain: automation
  input:
    lampen:
      name: Lampen
      description: "Selecteer één of meerdere lampen die moeten worden gecontroleerd."
      selector:
        target:
          entity:
            domain: light
    uitschakeltijd:
      name: Uitschakeltijd (in seconden)
      description: "Hoe lang moet de lamp aanblijven voordat deze automatisch wordt uitgeschakeld?"
      default: 60
      selector:
        number:
          min: 1
          max: 3600
          unit_of_measurement: seconds
          mode: slider

trigger:
  - platform: state
    entity_id: !input lampen
    from: 'off'
    to: 'on'
  - platform: state
    entity_id: !input lampen
    from: 'unavailable'
    to: 'on'

condition: []

action:
  - delay: !input uitschakeltijd
  - service: light.turn_off
    target:
        entity_id: !input lampen

mode: single
