blueprint:
  name: Lamp Timer Uitschakeling met Custom Actions
  description: "Schakelt een lamp uit na een ingestelde tijd als deze handmatig is aangezet, met optionele custom acties."
  domain: automation
  input:
    lampen:
      name: Lampen
      description: "Selecteer één of meerdere lampen die moeten worden gecontroleerd."
      selector:
        target:
          entity:
            domain: light
    uitschakeltijd:
      name: Uitschakeltijd (in seconden)
      description: "Hoe lang moet de lamp aanblijven voordat deze automatisch wordt uitgeschakeld?"
      default: 60
      selector:
        number:
          min: 1
          max: 3600
          unit_of_measurement: seconds
    custom_action:
      name: Custom Actie
      description: "Voer een custom actie uit nadat de lamp is uitgeschakeld."
      default: none
      selector:
        action: {}

trigger:
  - platform: state
    entity_id: !input lampen
    from: 'off'
    to: 'on'
  - platform: state
    entity_id: !input lampen
    from: 'unavailable'
    to: 'on'

condition: []

action:
  - delay: !input uitschakeltijd
  - service: light.turn_off
    target: !input lampen
  - if:
      - condition: template
        value_template: "{{ !is_state('none', !input custom_action) }}"
    then: !input custom_action

mode: single
