blueprint:
  name: Lamp Timer Uitschakeling
  description: "Schakelt een lamp uit na een ingestelde tijd als deze handmatig is aangezet."
  domain: automation
  input:
    lampen:
      name: Lampen
      description: "Selecteer één of meerdere lampen die moeten worden gecontroleerd."
      selector:
        target:
          entity:
            domain: light
    uitschakeltijd:
      name: Uitschakeltijd (in seconden)
      description: "Hoe lang moet de lamp aanblijven voordat deze automatisch wordt uitgeschakeld?"
      default: 300
      selector:
        number:
          min: 10
          max: 3600
          unit_of_measurement: seconds

trigger:
  - platform: state
    entity_id: !input lampen
    from: 'off'
    to: 'on'

action:
  - delay: "00:{{ ( !input uitschakeltijd // 60 ) | int }}:{{ !input uitschakeltijd % 60 }}"
  - service: light.turn_off
    target: !input lampen

mode: restart
