blueprint:
  name: Voltage Notification
  description: >
    Stuur een melding naar een apparaat wanneer de spanning van een sensor boven een bepaalde waarde komt.
    Blueprint versie: 1.06
  domain: automation
  input:
    voltage_sensor:
      name: Voltage Sensor
      description: Kies de sensor die de spanning meet.
      selector:
        entity:
          domain: sensor
          device_class: voltage
    voltage_threshold:
      name: Spanningsdrempel
      description: De waarde waarbij de notificatie wordt verzonden.
      default: 230
      selector:
        number:
          min: 0
          max: 400
          unit_of_measurement: V
    notify_device:
      name: Apparaat voor notificaties
      description: Kies een apparaat dat notificaties ontvangt. Het apparaat moet verbonden zijn met de Home Assistant mobiele app.
      selector:
        device:
          filter:
            integration: mobile_app
    notification_message:
      name: Notificatiebericht
      description: Het bericht dat naar het apparaat wordt gestuurd wanneer de drempel is overschreden. Je kunt de waarde van de spanning toevoegen met `{{ states('sensor.voltage_sensor') }} V`.
      default: "De spanning is te hoog!"
      selector:
        text:
          multiline: true

trigger:
  - platform: numeric_state
    entity_id: !input voltage_sensor
    above: !input voltage_threshold

variables:
  voltage_value: "{{ states( !input voltage_sensor ) }}"

action:
  - alias: "Stuur notificatie naar apparaat"
    service: notify.mobile_app_{{ states('device_tracker.{{ !input notify_device }}') }}
    data:
      message: >
        {{ !input notification_message }} 
        Huidige spanning: {{ voltage_value }} V
    title: "Spanningsalarm"

mode: single
