# Versie: scene006
blueprint:
  name: Scène Opslag met Volledige Status van Lampen
  description: "Maakt een snapshot van geselecteerde lampen met een unieke tijd-ID."
  domain: automation
  input:
    target_lights:
      name: Te selecteren lampen
      description: Selecteer de lampen waarvan je de volledige status wilt opslaan.
      selector:
        target:
          device:
            integration: light
            domain: light

mode: single

trigger:
  platform: event
  event_type: scene_snapshot

variables:
  entity_ids: >-
    {% set devices = device_entities(input.target_lights.device_id) %}
    {{ devices | join(', ') }}

action:
  - service: scene.create
    data:
      scene_id: "snapshot_{{ now().strftime('%Y%m%d%H%M%S') }}"
      snapshot_entities: "{{ entity_ids }}"
