# Blueprint Versie: 004
blueprint:
  name: Scène Opslag met Volledige Status van Lampen
  description: "Maakt een snapshot van geselecteerde lampen met een unieke tijd-ID."
  domain: automation
  input:
    target_lights:
      name: Te selecteren lampen
      description: Selecteer de lampen waarvan je de volledige status wilt opslaan.
      selector:
        target:
          entity:
            domain: light

mode: single

trigger:
  platform: event
  event_type: scene_snapshot

variables:
  lamp_entities: "{{ device_entities(input.target_lights.device_id) }}"

action:
  - service: scene.create
    data:
      scene_id: "snapshot_{{ now().strftime('%Y%m%d%H%M%S') }}"
      snapshot_entities: "{{ expand(lamp_entities) | map(attribute='entity_id') | join(', ') }}"
