# Versie: scene001
blueprint:
  name: Test Scène Opslag Lampen
  description: "Slaat de huidige status van geselecteerde lampen op in een scène."
  domain: automation
  input:
    target_lights:
      name: Te selecteren lampen
      description: Selecteer de lampen waarvan je de status wilt opslaan.
      selector:
        target:
          entity:
            domain: light

mode: single

trigger:
  platform: event
  event_type: scene_snapshot

action:
  - service: scene.create
    data:
      scene_id: >-
        {% set x = 'abcdefghijklmnopqrstuvwxyz' %} 
        {% set ns = namespace(name='scene_test_') %} 
        {% for i in range(8) %} 
          {% set ns.name = ns.name + x | random %} 
        {% endfor %} 
        {{ ns.name }}
      snapshot_entities: "{{ expand(target_lights.entity_id) | map(attribute='entity_id') | join(', ') }}"
