# Versie: scene007
blueprint:
  name: Scène Opslag met Volledige Status van Lampen
  description: "Maakt een snapshot van geselecteerde lampen met een unieke tijd-ID."
  domain: automation
  input:
    target_lights:
      name: Te selecteren lampen
      description: Selecteer de lampen waarvan je de volledige status wilt opslaan.
      selector:
        target:
          entity:
            domain: light
            multiple: true

mode: single

trigger:
  platform: event
  event_type: scene_snapshot

variables:
  entity_ids: "{{ expand(device_entities(input.target_lights.entity_id)) | map(attribute='entity_id') | join(', ') }}"

action:
  - service: scene.create
    data:
      scene_id: "snapshot_{{ now().strftime('%Y%m%d%H%M%S') }}"
      snapshot_entities: "{{ entity_ids }}"
