blueprint:
  name: Lamp Schakelen op Sensorwaarde
  description: "Schakelt een lamp aan of uit afhankelijk van de statusverandering van een geselecteerde sensor, schakelaar of knop."
  domain: automation
  input:
    sensor_entity:
      name: Sensor, Schakelaar of Knop
      description: "Selecteer de sensor, schakelaar of knop die de statusverandering activeert."
      selector:
        entity:
          domain: binary_sensor

    lamp_entity:
      name: Lamp
      description: "Selecteer de lamp die je wilt schakelen."
      selector:
        entity:
          domain: light

trigger:
  - platform: state
    entity_id: !input sensor_entity

action:
  - service: light.toggle
    target:
      entity_id: !input lamp_entity
