blueprint:
  name: "Voltage Monitoring en Melding"
  description: >
    Monitoren van spanning en versturen van meldingen bij overschrijding van een ingestelde grens.
    Bij overschrijding van de drempel wordt een melding verstuurd naar een specifieke gebruiker en wordt
    een log bijgehouden van het maximaal bereikte voltage.

    Versie: 1.13
    Update log:
      - Opgelost: Verwijdering van sjablonen in de logbook-actie om 'Message malformed' fout te vermijden.
      - Versienummer bijgewerkt naar 1.13.

  domain: automation

  input:
    voltage_sensors:
      name: Spanning sensoren
      description: Kies de spanning sensoren die gemonitord moeten worden.
      selector:
        entity:
          domain: sensor
          device_class: voltage
          multiple: true

    threshold:
      name: Spanning drempel
      description: >
        Stel de drempelwaarde in waarbij een melding wordt verstuurd. Standaard ingesteld op 245 volt.
        Zodra de netspanning bij u boven 253 Volt komt, schakelt de omvormer uit veiligheid af. Met als 
        gevolg dat er ook geen stroom meer opgewekt kan worden. Dit is wettelijk geregeld en staat beschreven 
        in de normen waar een omvormer aan moet voldoen.
      default: 245
      selector:
        number:
          min: 220
          max: 253
          unit_of_measurement: V
          step: 1

    notify_device:
      name: Apparaat om notificatie naar te sturen
      description: Het apparaat moet de Home Assistant mobiele app hebben geïnstalleerd.
      selector:
        device:
          integration: mobile_app

trigger:
  - platform: numeric_state
    entity_id: !input voltage_sensors
    above: !input threshold

action:
  - alias: "Send notification"
    domain: mobile_app
    type: notify
    device_id: !input notify_device
    message: >
      De spanningsdrempel is overschreden door {{ !input voltage_sensors }} met een waarde van {{ states(!input voltage_sensors) | string }} volt.
      Let op, de zonnepanelen kunnen minder opwekken als er niet wat verandert.

  - service: logbook.log
    data:
      name: "Spanning overschrijding"
      message: "De sensor {{ !input voltage_sensors }} heeft de spanningsdrempel overschreden."
