blueprint:
  name: Eenvoudige Voltage Melding
  description: >
    Stuur een melding naar de mobiele app zodra de spanning boven de ingestelde drempelwaarde komt.

  domain: automation

  input:
    voltage_sensor:
      name: Spanning sensor
      description: Selecteer de sensor die gemonitord moet worden.
      selector:
        entity:
          domain: sensor
          device_class: voltage

    threshold:
      name: Drempelwaarde
      description: Stel de drempelwaarde in (in volt) waarbij een melding moet worden verstuurd.
      default: 245
      selector:
        number:
          min: 200
          max: 253
          unit_of_measurement: V
          step: 1

    notify_device:
      name: Apparaat om notificatie naar te sturen
      description: Selecteer de apparaten die de melding moeten ontvangen.
      selector:
        device:
          integration: mobile_app
          multiple: true

trigger:
  - platform: numeric_state
    entity_id: !input voltage_sensor
    above: !input threshold

action:
  - repeat:
      for_each: !input notify_device
      sequence:
        - service: "notify.mobile_app_{{ device_attr(repeat.item, 'name') | slugify }}"
          data:
            message: >
              De spanning is nu {{ states(!input voltage_sensor) }} volt, wat de drempel van {{ !input threshold }} volt overschrijdt. Controleer de netspanning.
