blueprint:
  name: Insectenlamp Automatisering
  description: >
    Automatisering voor insectenlampen op basis van weer, seizoenen en handmatige bediening. Versie 3.02.
  domain: automation
  input:

    # Insectenlamp sectie
    insectenlampen_section:
      name: Insectenlampen Instellingen
      icon: mdi:lightbulb
      collapsed: true
      input:
        insectenlampen:
          name: Insectenlampen
          description: Selecteer de insectenlampen die je wilt aansturen.
          selector:
            target:
              entity:
                domain: switch

    # Weersensor sectie
    weersensor_section:
      name: Weersensor Instellingen
      icon: mdi:weather-cloudy
      collapsed: true
      input:
        weersensor:
          name: Weersensor
          description: Selecteer de weersensor die temperatuur, luchtvochtigheid en regen meet.
          selector:
            entity:
              domain: weather

    # Hysteresis instellen
    hysteresis_section:
      name: Hysteresis Instellingen
      icon: mdi:thermometer-lines
      collapsed: true
      input:
        hysteresis:
          name: Hysteresis
          description: "Stel de hysteresis in om te voorkomen dat de lampen te vaak schakelen."
          default: 0.5
          selector:
            number:
              min: 0.1
              max: 5.0
              step: 0.1
              unit_of_measurement: "°C"
    
    # Fallback-waarden voor temperatuur
    variables:
      binnentemperatuur: >
        {% set temp = states('sensor.binnen_temp_sensor') %}
        {% if temp not in ['unknown', 'unavailable'] %}
          {{ temp | float }}
        {% else %}
          {{ 21.0 }}  # Fallback-waarde als de sensor geen data geeft
        {% endif %}
    
      buiten_temp: >
        {% set temp = state_attr('weather.buienradar', 'temperature') %}
        {% if temp is not none %}
          {{ temp | float }}
        {% else %}
          {{ 15.0 }}  # Fallback-waarde voor buitentemperatuur
        {% endif %}

trigger:
  - platform: state
    entity_id: !input 'weersensor'

condition:
  - condition: numeric_state
    entity_id: !input 'weersensor'
    attribute: temperature
    above: !input 'min_temp'
    below: !input 'max_temp'

  - condition: numeric_state
    entity_id: !input 'weersensor'
    attribute: humidity
    above: !input 'min_humidity'
  
  - condition: numeric_state
    entity_id: !input 'weersensor'
    attribute: precipitation
    below: !input 'max_rain'

action:
  - choose:
      - conditions:
          - condition: state
            entity_id: !input 'seizoensmodus'
            state: 'Zomer'
        sequence:
          - service: switch.turn_on
            target: !input 'insectenlampen'
          - delay:
              minutes: !input 'overwerktimer'
          - service: switch.turn_off
            target: !input 'insectenlampen'
          
      - conditions:
          - condition: state
            entity_id: !input 'seizoensmodus'
            state: 'Winter'
        sequence:
          - service: switch.turn_on
            target: !input 'insectenlampen'
          - delay:
              minutes: !input 'winter_cyclus_duratie'
          - service: switch.turn_off
            target: !input 'insectenlampen'
          - delay:
              minutes: !input 'winter_uit_duratie'

mode: single
