blueprint:
  name: Insectenlamp Automatisering
  description: >
    Automatische bediening van insectenlampen op basis van weer, seizoenen en handmatige bediening. Versie 3.12.
  domain: automation
  input:

    insectenlampen:
      name: Insectenlampen
      description: Selecteer de insectenlampen die je wilt aansturen.
      selector:
        target:
          entity:
            domain: switch

    weersensor:
      name: Weersensor
      description: Selecteer de weersensor die temperatuur, luchtvochtigheid en regen meet.
      selector:
        entity:
          domain: weather

    min_temp:
      name: Minimale Temperatuur
      description: Stel de minimumtemperatuur in waarbij de insectenlampen nog geactiveerd worden.
      default: 10
      selector:
        number:
          min: -20
          max: 40
          unit_of_measurement: '°C'
    
    max_temp:
      name: Maximale Temperatuur
      description: Stel de maximumtemperatuur in waarbij de insectenlampen nog geactiveerd worden.
      default: 35
      selector:
        number:
          min: -20
          max: 50
          unit_of_measurement: '°C'

    min_humidity:
      name: Minimale Luchtvochtigheid
      description: Stel de minimum luchtvochtigheid in waarbij de insectenlampen nog geactiveerd worden.
      default: 60
      selector:
        number:
          min: 40
          max: 100
          unit_of_measurement: "%"

    max_rain:
      name: Maximale Regenintensiteit
      description: Stel de maximale regenintensiteit in waarbij de lampen nog worden ingeschakeld.
      default: 0.5
      selector:
        number:
          min: 0
          max: 10
          unit_of_measurement: "mm/h"

    vacation_mode:
      name: Vakantieschakelaar
      description: >
        Schakel de vakantiemodus in. Als deze modus is ingeschakeld, blijven de insectenlampen uit.
      selector:
        entity:
          domain: input_boolean

    seizoensmodus:
      name: Seizoensmodus
      description: Selecteer de seizoensmodus (Zomerstand, Winterstand).
      selector:
        entity:
          domain: input_select

    insect_lamp_duration:
      name: Tijd dat de lamp aan blijft (in minuten)
      description: >
        Stel de duur in dat de insectenlamp aanblijft wanneer deze geactiveerd wordt.
        Het advies is 15 minuten per activatie.
      default: 15
      selector:
        number:
          min: 5
          max: 60
          unit_of_measurement: "minuten"

    insect_lamp_cycles:
      name: Aantal activatiecycli per avond
      description: >
        Stel in hoe vaak de insectenlamp per avond geactiveerd moet worden.
        Het advies is 4 keer per avond.
      default: 4
      selector:
        number:
          min: 1
          max: 10
          unit_of_measurement: "cycli"

trigger:
  - platform: state
    entity_id: !input 'weersensor'
    attribute: temperature

condition:
  - condition: numeric_state
    entity_id: !input 'weersensor'
    attribute: temperature
    above: !input 'min_temp'
    below: !input 'max_temp'
  
  - condition: numeric_state
    entity_id: !input 'weersensor'
    attribute: humidity
    above: !input 'min_humidity'

  - condition: numeric_state
    entity_id: !input 'weersensor'
    attribute: precipitation
    below: !input 'max_rain'

action:
  - service: switch.turn_on
    target: !input 'insectenlampen'
  
  - delay:
      minutes: !input 'insect_lamp_duration'

  - repeat:
      count: !input 'insect_lamp_cycles'
      sequence:
        - delay: "00:30:00"  # Pauze tussen cycli
        - service: switch.turn_on
          target: !input 'insectenlampen'

mode: single
