blueprint:
  name: Insectenlamp Automatisering Versie 2.01
  description: >
    Automatische bediening van insectenlampen op basis van temperatuur, luchtvochtigheid, UV-straling, neerslag, en seizoenen.
    Optimaliseert de tijd en duur waarop de lampen aan staan, en houdt rekening met de activiteit van insecten.
    Gebruik standaardwaarden of pas ze aan om de configuratie naar wens te tweaken.
  domain: automation
  input:
    # Sectie Insectenlampen
    insect_lamps:
      name: Apparaten voor Insectenbestrijding
      description: >
        Selecteer de insectenlampen die je wilt aansturen.
      selector:
        target:
          entity:
            domain:
              - switch
              - light
          multiple: true

    # Sectie Weersensor
    weather_sensor:
      name: Weersensor
      description: >
        Selecteer de weersensor die temperatuur, luchtvochtigheid, en neerslag meet.
        Voorbeelden van sensoren zijn Buienradar of een andere weersensor.
      selector:
        entity:
          domain: weather

    # Sectie Tweak
    min_temp:
      name: Minimale Temperatuur voor Activatie (in °C)
      description: >
        Stel de minimumtemperatuur in waarbij insecten actief worden. Standaard is 20°C.
      default: 20
      selector:
        number:
          min: 10
          max: 35
          unit_of_measurement: °C

    max_temp:
      name: Maximale Temperatuur voor Activatie (in °C)
      description: >
        Stel de maximumtemperatuur in waarbij insecten actief zijn. Standaard is 35°C.
      default: 35
      selector:
        number:
          min: 20
          max: 45
          unit_of_measurement: °C

    min_humidity:
      name: Minimale Luchtvochtigheid voor Activatie (in %)
      description: >
        Stel de minimum luchtvochtigheid in waarbij insecten actief worden. Standaard is 60%.
      default: 60
      selector:
        number:
          min: 40
          max: 100
          unit_of_measurement: %

    insect_lamp_duration:
      name: Duur van de Insectenlampen (in minuten)
      description: >
        De tijdsduur dat de insectenlampen aan moeten blijven na detectie van insectenactiviteit.
      default: 10
      selector:
        number:
          min: 1
          max: 60
          unit_of_measurement: 'min'

    manual_override_sensor:
      name: Handmatige Inschakeling Sensor (Optioneel)
      description: >
        Selecteer een sensor die handmatig de lampen kan in- en uitschakelen voor een bepaalde tijd.
        Dit veld is optioneel en kan worden weggelaten als je geen handmatige bediening wilt.
      selector:
        entity:
          domain: binary_sensor
          multiple: false

    vacation_mode:
      name: Vakantieschakelaar
      description: >
        Schakelt de vakantiemodus in of uit via een dashboardknop.
      selector:
        entity:
          domain: input_boolean

    # Optional input for manual override
    manual_override_duration:
      name: Duur van Handmatige Inschakeling (in minuten)
      description: >
        De tijdsduur dat de lampen handmatig ingeschakeld moeten blijven via de handmatige sensor.
      default: 30
      selector:
        number:
          min: 1
          max: 120
          unit_of_measurement: 'min'

trigger:
  - platform: state
    entity_id: !input manual_override_sensor
    to: "on"

condition:
  - condition: and
    conditions:
      - condition: state
        entity_id: !input vacation_mode
        state: "off"

action:
  - choose:
      - conditions:
          - condition: state
            entity_id: !input weather_sensor
            attribute: temperature
            below: !input min_temp
          - condition: state
            entity_id: !input weather_sensor
            attribute: humidity
            above: !input min_humidity
        sequence:
          - service: switch.turn_on
            target: !input insect_lamps
          - delay: "00:{{ !input insect_lamp_duration | int }}"
          - service: switch.turn_off
            target: !input insect_lamps

    - conditions:
        - condition: state
          entity_id: !input manual_override_sensor
          state: "on"
      sequence:
        - service: switch.turn_on
          target: !input insect_lamps
        - delay: "00:{{ !input manual_override_duration | int }}"
        - service: switch.turn_off
          target: !input insect_lamps

mode: single
