blueprint:
  name: Insectenlamp Automatisering Versie 2.01
  description: >
    Automatische bediening van insectenlampen op basis van temperatuur, luchtvochtigheid, UV-straling, neerslag, en seizoenen.
    Optimaliseert de tijd en duur waarop de lampen aan staan, en houdt rekening met de activiteit van insecten.
    Gebruik standaardwaarden of pas ze aan om de configuratie naar wens te tweaken.
  domain: automation
  input:
    # Sectie Insectenlampen
    insect_lamps:
      name: Apparaten voor Insectenbestrijding
      description: >
        Selecteer de insectenlampen die je wilt aansturen.
      selector:
        target:
          entity:
            domain:
              - switch
              - light
          multiple: true

    # Sectie Weersensor
    weather_sensor:
      name: Weersensor
      description: >
        Selecteer de weersensor die temperatuur, luchtvochtigheid, en neerslag meet.
        Voorbeelden van sensoren zijn Buienradar of een andere weersensor.
      selector:
        entity:
          domain: weather

    # Sectie Tweak
    min_temp:
      name: Minimale Temperatuur voor Activatie (in °C)
      description: >
        Stel de minimumtemperatuur in waarbij insecten actief worden. Standaard is 20°C.
      default: 20
      selector:
        number:
          min: 10
          max: 35
          unit_of_measurement: "°C"

    max_temp:
      name: Maximale Temperatuur voor Activatie (in °C)
      description: >
        Stel de maximumtemperatuur in waarbij insecten actief zijn. Standaard is 35°C.
      default: 35
      selector:
        number:
          min: 20
          max: 45
          unit_of_measurement: "°C"

    min_humidity:
      name: Minimale Luchtvochtigheid voor Activatie (in %)
      description: >
        Stel de minimum luchtvochtigheid in waarbij insecten actief worden. Standaard is 60%.
      default: 60
      selector:
        number:
          min: 40
          max: 100
          unit_of_measurement: "%"
          
    insect_lamp_duration:
      name: Insectenlamp Duur
      description: >
        De tijdsduur dat de insectenlampen aan moeten blijven na detectie van activiteit. Gebruik het formaat 'HH:MM:SS'.
      default: "00:30:00"
      selector:
        duration:

    manual_override:
      name: Handmatige Bediening
      description: >
        Optioneel: Selecteer een schakelaar of sensor die de lampen handmatig kan in- of uitschakelen voor een bepaalde tijd.
      selector:
        entity:
          domain: switch
          multiple: false

trigger:
  - platform: state
    entity_id: !input motion_sensor
    to: "on"

condition:
  - condition: and
    conditions:
      - condition: numeric_state
        entity_id: !input weather_sensor
        attribute: temperature
        above: !input min_temp
      - condition: numeric_state
        entity_id: !input weather_sensor
        attribute: temperature
        below: !input max_temp
      - condition: numeric_state
        entity_id: !input weather_sensor
        attribute: humidity
        above: !input min_humidity
      - condition: template
        value_template: >
          {% if not is_state('input_boolean.vakantie', 'on') %}
            {% set temp = state_attr(!input weather_sensor, 'temperature') %}
            {% set humidity = state_attr(!input weather_sensor, 'humidity') %}
            {% set precipitation = state_attr(!input weather_sensor, 'precipitation') %}
            {{ temp > min_temp and temp < max_temp and humidity > min_humidity and precipitation > 0 }}
          {% else %}
            false
          {% endif %}

action:
  - choose:
      - conditions:
          - condition: state
            entity_id: !input manual_override
            state: "on"
        sequence:
          - service: switch.turn_on
            target: !input insect_lamps
          - delay: !input insect_lamp_duration
          - service: switch.turn_off
            target: !input insect_lamps
      - conditions:
          - condition: state
            entity_id: input_select.seizoensmodus
            state: "Zomerstand"
        sequence:
          - service: switch.turn_on
            target: !input insect_lamps
          - delay: "00:30:00"
          - service: switch.turn_off
            target: !input insect_lamps
      - conditions:
          - condition: state
            entity_id: input_select.seizoensmodus
            state: "Winterstand"
        sequence:
          - service: switch.turn_on
            target: !input insect_lamps
          - delay: "00:05:00"
          - service: switch.turn_off
            target: !input insect_lamps
