blueprint:
  name: Ventilatie en Mechanische Ventilatie
  description: Regelt ventilatoren en mechanische ventilatie op basis van temperatuur en weersomstandigheden
  domain: automation
  input:
    woonkamer_ventilator:
      name: Woonkamer Ventilator
      description: De ventilator in de woonkamer
      selector:
        entity:
          domain: switch
    slaapkamer_ventilator:
      name: Slaapkamer Ventilator
      description: De ventilator in de slaapkamer
      selector:
        entity:
          domain: switch
    kantoor_ventilator:
      name: Kantoor Ventilator
      description: De ventilator in het kantoor
      selector:
        entity:
          domain: switch
    zolder_ventilator:
      name: Zolder Ventilator
      description: De ventilator op de zolder
      selector:
        entity:
          domain: switch
    buitentemperatuur_sensor:
      name: Buitentemperatuur Sensor
      description: De sensor voor de buitentemperatuur (mag geen weather.buienradar zijn)
      selector:
        entity:
          domain: sensor
    eerste_weersensor:
      name: Eerste Weersensor
      description: De eerste weersensor (mag geen weather.buienradar zijn)
      selector:
        entity:
          domain: weather
    tweede_weersensor:
      name: Tweede Weersensor
      description: De tweede weersensor (mag geen weather.buienradar zijn)
      selector:
        entity:
          domain: weather
    temperatuur_marge:
      name: Temperatuur Marge
      description: De marge rond de gewenste temperatuur
      default: 0.5
      selector:
        number:
          min: 0
          max: 5
          step: 0.1
    overwerktimer_tijd:
      name: Overwerktimer Tijd
      description: De tijd in minuten dat een handmatig ingeschakelde ventilator niet door het script wordt beïnvloed
      default: 15
      selector:
        number:
          min: 1
          max: 60
          step: 1

trigger:
  - platform: time_pattern
    minutes: '/15'

condition:
  - condition: and
    conditions:
      - condition: state
        entity_id: "{{ input('woonkamer_ventilator') }}"
        state: 'on'
      - condition: state
        entity_id: "{{ input('slaapkamer_ventilator') }}"
        state: 'on'
      - condition: state
        entity_id: "{{ input('kantoor_ventilator') }}"
        state: 'on'
      - condition: state
        entity_id: "{{ input('zolder_ventilator') }}"
        state: 'on'

action:
  - choose:
      - conditions:
          - condition: template
            value_template: >
              {% set temp_w = states('sensor.binnen_temperatuur_woonkamer') | float %}
              {% set temp_s = states('sensor.binnen_temperatuur_slaapkamer') | float %}
              {% set temp_k = states('sensor.binnen_temperatuur_kantoor') | float %}
              {% set temp_z = states('sensor.binnen_temperatuur_zolder') | float %}
              {% set buitentemp = states('sensor.buitentemperatuur_sensor') | float %}
              {% set marge = state('input_number.temperatuur_marge') | float %}
              {% set gewenste_temp_w = state('input_number.gewenste_temperatuur_woonkamer') | float %}
              {% set gewenste_temp_s = state('input_number.gewenste_temperatuur_slaapkamer') | float %}
              {% set gewenste_temp_k = state('input_number.gewenste_temperatuur_kantoor') | float %}
              {% set gewenste_temp_z = state('input_number.gewenste_temperatuur_zolder') | float %}
              (temp_w < (gewenste_temp_w - marge) or temp_w > (gewenste_temp_w + marge)) or
              (temp_s < (gewenste_temp_s - marge) or temp_s > (gewenste_temp_s + marge)) or
              (temp_k < (gewenste_temp_k - marge) or temp_k > (gewenste_temp_k + marge)) or
              (temp_z < (gewenste_temp_z - marge) or temp_z > (gewenste_temp_z + marge))
        sequence:
          - service: switch.turn_on
            target:
              entity_id: >
                {% if temp_w < (gewenste_temp_w - marge) %}
                  {{ input('woonkamer_ventilator') }}
                {% endif %}
                {% if temp_s < (gewenste_temp_s - marge) %}
                  {{ input('slaapkamer_ventilator') }}
                {% endif %}
                {% if temp_k < (gewenste_temp_k - marge) %}
                  {{ input('kantoor_ventilator') }}
                {% endif %}
                {% if temp_z < (gewenste_temp_z - marge) %}
                  {{ input('zolder_ventilator') }}
                {% endif %}
          - service: switch.turn_off
            target:
              entity_id: >
                {% if temp_w > (gewenste_temp_w + marge) %}
                  {{ input('woonkamer_ventilator') }}
                {% endif %}
                {% if temp_s > (gewenste_temp_s + marge) %}
                  {{ input('slaapkamer_ventilator') }}
                {% endif %}
                {% if temp_k > (gewenste_temp_k + marge) %}
                  {{ input('kantoor_ventilator') }}
                {% endif %}
                {% if temp_z > (gewenste_temp_z + marge) %}
                  {{ input('zolder_ventilator') }}
                {% endif %}

    # Voeg hier de logica toe voor mechanische ventilatie indien van toepassing
    # Hier kunnen we later de code toevoegen die betrekking heeft op de mechanische ventilatie

