blueprint:
  name: "High Voltage Notification"
  description: "Stuur een melding als een sensor voltage boven een bepaalde drempelwaarde komt."
  domain: automation
  input:
    voltage_sensor:
      name: Voltage Sensor
      description: "Kies de sensor die de voltage meet."
      selector:
        entity:
          domain: sensor
    voltage_threshold:
      name: Voltage Drempelwaarde
      description: "De drempelwaarde waarbij de melding wordt verzonden."
      default: 220
      selector:
        number:
          min: 0
          max: 500
          unit_of_measurement: V
    notify_device:
      name: Apparaat om te notificeren
      description: "Kies het mobiele apparaat waarop de melding wordt ontvangen."
      selector:
        device:
          integration: mobile_app

trigger:
  - platform: numeric_state
    entity_id: !input voltage_sensor
    above: !input voltage_threshold

action:
  - service: notify.mobile_app_{{ device_id }}
    data:
      title: "⚠️ Hoge Voltage Gedetecteerd!"
      message: "{{ state_attr(!input voltage_sensor, 'friendly_name') }} heeft een voltage van {{ states(!input voltage_sensor) }} V overschreden."
      data:
        actions:
          - action: "timestamp"
            title: "Noteer tijdstip en voltage"
          - action: "snooze"
            title: "Snooze (30 minuten)"
          - action: "ignore_day"
            title: "Negeer de hele dag"

# Voor de actieknoppen
mode: single
