blueprint:
  name: "High Voltage Notification"
  description: "Stuur een notificatie naar een mobiel apparaat wanneer de voltage van een sensor een bepaalde drempelwaarde overschrijdt."
  domain: automation
  input:
    voltage_sensor:
      name: Voltage Sensor
      description: "Kies de sensor die de voltage meet."
      selector:
        entity:
          domain: sensor
    voltage_threshold:
      name: Voltage Drempelwaarde
      description: "De drempelwaarde waarbij de melding wordt verzonden."
      default: 220
      selector:
        number:
          min: 0
          max: 500
          unit_of_measurement: V
    notify_device:
      name: Apparaat om te notificeren
      description: "Selecteer het apparaat dat de notificatie moet ontvangen."
      selector:
        device:
          integration: mobile_app
    notify_title:
      name: Titel van de notificatie
      description: "De titel van de notificatie."
      default: "âš ï¸ Hoge Voltage Gedetecteerd!"
      selector:
        text:
    notify_okay_message:
      name: Bericht als alles in orde is
      description: "Bericht dat verstuurd wordt wanneer de voltage binnen de grenzen blijft."
      default: "De voltage is weer normaal."
      selector:
        text:

trigger:
  - platform: numeric_state
    entity_id: !input voltage_sensor
    above: !input voltage_threshold

action:
  - service: "notify.mobile_app_{{ device_attr(!input notify_device, 'name') | slugify }}"
    data:
      title: !input notify_title
      message: >
        De voltage van {{ state_attr(!input voltage_sensor, 'friendly_name') }} is nu 
        {{ states(!input voltage_sensor) }} V en heeft de drempel van {{ !input voltage_threshold }} V overschreden.
