blueprint:
  name: Control Light with Hue Saturation
  description: A blueprint to control light using Hue-Saturation mode only.
  domain: automation
  input:
    controller:
      name: (Required) Controller
      description: The controller to use for this automation.
      selector:
        entity:
          domain: sensor
    controller_model:
      name: (Required) Controller model
      description: The model for the controller used in this automation. Choose a value from the list of supported controllers.
      selector:
        select:
          options:
            - IKEA E2001/E2002 STYRBAR Remote control
            - IKEA E2001/E2002 STYRBAR Remote control (#2)
    light:
      name: (Required) Light
      description: Light which will be controlled with this automation.
      selector:
        entity:
          domain: light
    light_transition:
      name: (Optional) Light Transition
      description: Number that represents the time (in milliseconds) the light should take to turn on or off, if the light supports it.
      default: 250
      selector:
        number:
          min: 0
          max: 60000
          step: 1
          unit_of_measurement: milliseconds
          mode: box
    min_brightness:
      name: (Optional) Light minimum brightness
      description: The minimum brightness the light can be set with this automation.
      default: 1
      selector:
        number:
          min: 1
          max: 255
          step: 1
          unit_of_measurement: brightness
          mode: slider
    max_brightness:
      name: (Optional) Light maximum brightness
      description: The maximum brightness the light can be set with this automation.
      default: 255
      selector:
        number:
          min: 0
          max: 255
          step: 1
          unit_of_measurement: brightness
          mode: slider
    brightness_steps_short:
      name: (Optional) Light brightness steps - short actions
      description: Number of steps from min to max brightness when controlling brightness with short actions (e.g., button press).
      default: 10
      selector:
        number:
          min: 1
          max: 100
          step: 1
    brightness_steps_long:
      name: (Optional) Light brightness steps - long actions
      description: Number of steps from min to max brightness when controlling brightness with long actions (e.g., button hold).
      default: 10
      selector:
        number:
          min: 1
          max: 100
          step: 1

trigger:
  platform: state
  entity_id: !input controller

variables:
  light: !input light
  light_transition: !input light_transition
  min_brightness: !input min_brightness
  max_brightness: !input max_brightness
  brightness_steps_short: !input brightness_steps_short
  brightness_steps_long: !input brightness_steps_long

action:
  - choose:
      - conditions: '{{ trigger.entity_id == "controller" }}'
        sequence:
          - service: light.turn_on
            target:
              entity_id: !input light
            data:
              hs_color: '{{ [((state_attr(light,"hs_color")[0] or 0) + 15) % 360, 100] }}'
              transition: !input light_transition
  - choose:
      - conditions: '{{ trigger.entity_id == "controller" }}'
        sequence:
          - service: light.turn_on
            target:
              entity_id: !input light
            data:
              hs_color: '{{ [((state_attr(light,"hs_color")[0] or 0) - 15) % 360, 100] }}'
              transition: !input light_transition
mode: restart
max_exceeded: silent
