blueprint:
  name: Voltage Monitoring Notification
  description: "Stuur een melding naar je telefoon wanneer de spanning op fase 1 boven 231.0 V komt."
  domain: automation
  input:
    voltage_sensor:
      name: Voltage Sensor
      description: "Kies de voltage sensor die je wilt monitoren"
      selector:
        entity:
          domain: sensor
    notify_device:
      name: Device to notify
      description: "Selecteer het apparaat om de notificatie te ontvangen"
      selector:
        device:
          integration: mobile_app
    voltage_threshold:
      name: Voltage Threshold
      description: "Drempelwaarde voor voltage"
      default: 231.0
      selector:
        number:
          min: 0
          max: 250
          step: 0.1

trigger:
  - platform: numeric_state
    entity_id: !input voltage_sensor
    above: !input voltage_threshold

action:
  - service: notify.mobile_app_!input notify_device
    data:
      message: >
        De spanning op fase 1 is boven {{ states(!input voltage_sensor) }} V gestegen.
