blueprint:
  name: Voltage Monitoring Notification
  description: "Stuur een melding naar je telefoon wanneer de spanning op fase 1 boven 231.0 V komt."
  domain: automation
  input:
    voltage_sensor:
      name: Voltage Sensor
      description: "Kies de voltage sensor die je wilt monitoren."
      selector:
        entity:
          domain: sensor
    notify_device:
      name: Device to notify
      description: "Selecteer het apparaat waarop de notificatie moet worden gestuurd. Het apparaat moet de officiële Home Assistant-app gebruiken."
      selector:
        device:
          filter:
            integration: mobile_app
    voltage_threshold:
      name: Voltage Threshold
      description: "Drempelwaarde voor voltage."
      default: 231.0
      selector:
        number:
          min: 0
          max: 250
          step: 0.1

trigger:
  platform: numeric_state
  entity_id: !input voltage_sensor
  above: !input voltage_threshold

variables:
  voltage_sensor: !input voltage_sensor
  voltage_threshold: !input voltage_threshold
  current_voltage: "{{ states(voltage_sensor) }}"

action:
  - service: notify.mobile_app_!input notify_device
    data:
      message: >
        De spanning op fase 1 is boven de {{ voltage_threshold }} V gestegen.
        Huidige spanning: {{ current_voltage }} V
