blueprint:
  name: Insectenlamp Automatiserings-Blueprint
  description: Automatisering voor het bedienen van insectenlampen op basis van omgevingsfactoren zoals temperatuur, luchtvochtigheid, UV-straling, beweging en weersomstandigheden.
  domain: automation
  input:
    insect_lamps:
      name: Apparaten voor insectenbestrijding
      description: Selecteer alle apparaten die je wilt aansturen voor insectenbestrijding (insectenlampen, lampen, etc.).
      selector:
        target:
          entity:
            domain:
              - switch
              - light
            multiple: true

    weather_sensor:
      name: Weersensor
      description: Selecteer de weer-gerelateerde sensor die temperatuur en luchtvochtigheid meet.
      selector:
        entity:
          domain: weather

    temperature_min:
      name: Minimum Temperatuur
      description: Minimumtemperatuur waarbij de insectenlampen aan moeten gaan (in graden Celsius).
      default: 20
      selector:
        number:
          min: -10
          max: 40
          unit_of_measurement: '°C'

    temperature_max:
      name: Maximum Temperatuur
      description: Maximumtemperatuur waarbij de insectenlampen aan moeten gaan (in graden Celsius).
      default: 35
      selector:
        number:
          min: -10
          max: 40
          unit_of_measurement: '°C'

    humidity_threshold:
      name: Luchtvochtigheidsdrempel
      description: Luchtvochtigheid waarbij de insectenlampen aan moeten gaan (in %).
      default: 60
      selector:
        number:
          min: 0
          max: 100
          unit_of_measurement: '%'

    uv_sensor:
      name: UV-Straling sensor [Optioneel]
      description: Selecteer de sensor die UV-straling meet. Optioneel, alleen gebruiken als beschikbaar.
      selector:
        target:
          entity:
            domain: sensor

    soil_temperature_sensor:
      name: Grondtemperatuur sensor [Optioneel]
      description: Selecteer de sensor die de grondtemperatuur meet. Optioneel, alleen gebruiken als beschikbaar.
      selector:
        target:
          entity:
            domain: sensor

    rainfall_sensor:
      name: Neerslagintensiteit sensor [Optioneel]
      description: Selecteer de sensor die de neerslagintensiteit meet. Optioneel, alleen gebruiken als beschikbaar.
      selector:
        target:
          entity:
            domain: sensor

    vacation_mode:
      name: Vakantieschakelaar
      description: Schakelt de vakantiemodus in of uit. Wanneer ingeschakeld, blijven de insectenlampen uit, tenzij beweging of een thuisregistratie wordt gedetecteerd en de weersomstandigheden insectenactiviteit voorspellen.
      default: false
      selector:
        boolean:

    seasonal_mode:
      name: Seizoensmodus
      description: Wisselt automatisch tussen zomer- en wintermodus op basis van temperatuur en luchtvochtigheid.
      default: 'Zomerstand'
      selector:
        select:
          options:
            - Zomerstand
            - Winterstand

    emergency_switch:
      name: Noodbediening Insectenlamp
      description: Handmatige schakelaar om de insectenlamp in of uit te schakelen. Activeert de timer `timer.noodbediening_insectenlamp_timer` wanneer ingeschakeld.
      default: false
      selector:
        boolean:

    emergency_timer:
      name: Noodbediening Insectenlamp Timer
      description: Timer die de insectenlamp tijdelijk uitschakelt op verzoek van de noodbediening.
      default: 1:00:00
      selector:
        duration:

  trigger:
    - platform: state
      entity_id: !input 'weather_sensor'
      attribute: temperature

    - platform: state
      entity_id: !input 'weather_sensor'
      attribute: humidity

  condition:
    - condition: or
      conditions:
        - condition: numeric_state
          entity_id: !input 'weather_sensor'
          attribute: temperature
          above: !input 'temperature_min'
        - condition: numeric_state
          entity_id: !input 'weather_sensor'
          attribute: temperature
          below: !input 'temperature_max'
        - condition: numeric_state
          entity_id: !input 'weather_sensor'
          attribute: humidity
          above: !input 'humidity_threshold'

  action:
    - choose:
        - conditions:
            - condition: state
              entity_id: !input 'vacation_mode'
              state: 'on'
          sequence:
            - service: switch.turn_off
              target:
                entity_id: !input 'insect_lamps'
        - conditions:
            - condition: and
              conditions:
                - condition: numeric_state
                  entity_id: !input 'weather_sensor'
                  attribute: temperature
                  above: !input 'temperature_min'
                - condition: numeric_state
                  entity_id: !input 'weather_sensor'
                  attribute: temperature
                  below: !input 'temperature_max'
                - condition: numeric_state
                  entity_id: !input 'weather_sensor'
                  attribute: humidity
                  above: !input 'humidity_threshold'
          sequence:
            - service: switch.turn_on
              target:
                entity_id: !input 'insect_lamps'
            - delay:
                minutes: 10
            - service: switch.turn_off
              target:
                entity_id: !input 'insect_lamps'
    
    - choose:
        - conditions:
            - condition: state
              entity_id: !input 'emergency_switch'
              state: 'on'
          sequence:
            - service: switch.turn_off
              target:
                entity_id: !input 'insect_lamps'
            - delay: !input 'emergency_timer'
            - service: switch.turn_on
              target:
                entity_id: !input 'insect_lamps'
