blueprint:
  name: "Ventilatiesysteem 4.02"
  description: >
    Dit ventilatiesysteem regelt de ventilatoren in meerdere kamers op basis van 
    de binnentemperatuur, buitentemperatuur, neerslag en hysteresis. De ventilatoren 
    kunnen automatisch worden in- en uitgeschakeld op basis van temperatuurwijzigingen, 
    buitenluchttemperatuur en aanwezigheid via nabijheidssensoren.

    Versie: 4.02
    Motregen drempel: 0.3 mm/h. Pas deze waarde aan naar wens (regen bij 0.8 mm/h, harde regen bij 2.5 mm/h).
  domain: automation
  input:
    # Woonkamer parameters
    fan_switch_woonkamer:
      name: Ventilator Woonkamer
      description: "Entiteit van de schakelaar voor de ventilator in de woonkamer"
      selector:
        entity:
          domain: switch

    temp_sensor_woonkamer:
      name: Temperatuursensor Woonkamer
      description: "Entiteit van de temperatuursensor in de woonkamer"
      selector:
        entity:
          domain: sensor
          device_class: temperature

    desired_temp_woonkamer:
      name: Gewenste temperatuur Woonkamer
      description: "In te stellen temperatuur voor de woonkamer (standaard 21째C)"
      default: 21
      selector:
        number:
          min: 10
          max: 30
          unit_of_measurement: "째C"
          step: 0.5

    disable_rain_shutdown_woonkamer:
      name: Regen uitschakeling Woonkamer
      description: "Zet de ventilator uit bij regen in de woonkamer"
      default: false
      selector:
        boolean: {}

    # Globale instellingen
    hysteresis:
      name: Hysteresis
      description: "Globale hysteresis voor aan/uit-schakeling van ventilatoren"
      default: 0.5
      selector:
        number:
          min: 0.1
          max: 5
          unit_of_measurement: "째C"
          step: 0.1

    weather_sensor:
      name: Weersensor
      description: "De sensor die de neerslag en buitentemperatuur meet (bijv. Buienradar)"
      selector:
        entity:
          domain: weather

    rain_threshold:
      name: Drempelwaarde motregen
      description: "Standaard drempel voor motregen is 0.3 mm/h. Pas dit aan op basis van jouw situatie."
      default: 0.3
      selector:
        number:
          min: 0
          max: 5
          unit_of_measurement: "mm/h"
          step: 0.1

    vacation_mode:
      name: Vakantiemodus
      description: "Schakel de vakantiemodus in, indien van toepassing (optioneel)"
      selector:
        entity:
          domain: input_boolean

    proximity_sensor:
      name: Nabijheidssensor
      description: "De sensor die de nabijheid meet (bijv. BLE of GPS). Gebruik dit om ventilatie op basis van aanwezigheid te regelen."
      selector:
        entity:
          domain: sensor
          device_class: proximity

    outside_temperature_threshold:
      name: Buitentemperatuur Drempelwaarde
      description: "Drempelwaarde voor buitenluchttemperatuur. Ventilatoren schakelen aan als de temperatuur onder deze waarde zakt."
      default: 15
      selector:
        number:
          min: 5
          max: 30
          unit_of_measurement: "째C"
          step: 1

  trigger:
    # Trigger bij temperatuurwijziging in de woonkamer
    - platform: state
      entity_id: !input temp_sensor_woonkamer
      id: temperature_change

    # Trigger bij wijziging in weersensor (bijv. regen)
    - platform: state
      entity_id: !input weather_sensor
      id: weather_change

    # Trigger bij wijziging van de vakantiemodus
    - platform: state
      entity_id: !input vacation_mode
      id: vacation_mode_change

    # Trigger bij verandering van de nabijheidssensor
    - platform: state
      entity_id: !input proximity_sensor
      id: proximity_change

  condition:
    # Voorwaarde: Alleen activeren als vakantiemodus uitstaat
    - condition: state
      entity_id: !input vacation_mode
      state: "off"

  action:
    - choose:
        # Actie bij temperatuur onder de ingestelde waarde minus hysteresis
        - conditions:
            - condition: numeric_state
              entity_id: !input temp_sensor_woonkamer
              below: "{{ !input.desired_temp_woonkamer - !input.hysteresis }}"
          sequence:
            - service: switch.turn_on
              target:
                entity_id: !input fan_switch_woonkamer

        # Actie bij temperatuur boven de ingestelde waarde plus hysteresis
        - conditions:
            - condition: numeric_state
              entity_id: !input temp_sensor_woonkamer
              above: "{{ !input.desired_temp_woonkamer + !input.hysteresis }}"
          sequence:
            - service: switch.turn_off
              target:
                entity_id: !input fan_switch_woonkamer

    # Controleer op neerslag en schakel ventilator uit indien nodig
    - choose:
        - conditions:
            - condition: template
              value_template: >
                {{ states.weather.buienradar.attributes.precipitation > !input.rain_threshold }}
            - condition: state
              entity_id: !input disable_rain_shutdown_woonkamer
              state: "on"
          sequence:
            - service: switch.turn_off
              target:
                entity_id: !input fan_switch_woonkamer

    # Schakel ventilatoren in op basis van buitentemperatuur
    - choose:
        - conditions:
            - condition: numeric_state
              entity_id: !input weather_sensor
              attribute: temperature
              below: "{{ !input.outside_temperature_threshold }}"
          sequence:
            - service: switch.turn_on
              target:
                entity_id: !input fan_switch_woonkamer

    # Schakel ventilatoren uit als niemand in de buurt is
    - choose:
        - conditions:
            - condition: state
              entity_id: !input proximity_sensor
              state: "away"
          sequence:
            - service: switch.turn_off
              target:
                entity_id: !input fan_switch_woonkamer

  mode: single
