blueprint:
  name: "Ventilatiesysteem 4.05"
  description: >
    Dit ventilatiesysteem regelt de ventilatoren in meerdere kamers op basis van 
    de binnentemperatuur, buitentemperatuur, neerslag en hysteresis. De ventilatoren 
    kunnen automatisch worden in- en uitgeschakeld op basis van temperatuurwijzigingen, 
    buitenluchttemperatuur, aanwezigheid via nabijheidssensoren, en custom actions kunnen worden toegevoegd door de gebruiker.

    Versie: 4.05
    Motregen drempel: 0.3 mm/h. Pas deze waarde aan naar wens (regen bij 0.8 mm/h, harde regen bij 2.5 mm/h).
  domain: automation
  input:
    fan_switch_woonkamer:
      name: Ventilator Woonkamer
      description: "Entiteit van de schakelaar voor de ventilator in de woonkamer"
      selector:
        entity:
          domain: switch

    temp_sensor_woonkamer:
      name: Temperatuursensor Woonkamer
      description: "Entiteit van de temperatuursensor in de woonkamer"
      selector:
        entity:
          domain: sensor
          device_class: temperature

    desired_temp_woonkamer:
      name: Gewenste temperatuur Woonkamer
      description: "In te stellen temperatuur voor de woonkamer (standaard 21째C)"
      default: 21
      selector:
        number:
          min: 10
          max: 30
          unit_of_measurement: "째C"
          step: 0.5

    disable_rain_shutdown_woonkamer:
      name: Regen uitschakeling Woonkamer
      description: "Zet de ventilator uit bij regen in de woonkamer"
      default: false
      selector:
        boolean: {}

    hysteresis:
      name: Hysteresis
      description: "Globale hysteresis voor aan/uit-schakeling van ventilatoren"
      default: 0.5
      selector:
        number:
          min: 0.1
          max: 5
          unit_of_measurement: "째C"
          step: 0.1

    weather_sensor:
      name: Weersensor
      description: "De sensor die de neerslag en buitentemperatuur meet (bijv. Buienradar)"
      selector:
        entity:
          domain: weather

    rain_threshold:
      name: Drempelwaarde motregen
      description: "Standaard drempel voor motregen is 0.3 mm/h. Pas dit aan op basis van jouw situatie."
      default: 0.3
      selector:
        number:
          min: 0
          max: 5
          unit_of_measurement: "mm/h"
          step: 0.1

    vacation_mode:
      name: Vakantiemodus
      description: "Schakel de vakantiemodus in, indien van toepassing (optioneel)"
      selector:
        entity:
          domain: input_boolean

    proximity_sensor:
      name: Nabijheidssensor
      description: "De sensor die de nabijheid meet (bijv. BLE of GPS). Gebruik dit om ventilatie op basis van aanwezigheid te regelen."
      selector:
        entity:
          domain: sensor
          device_class: proximity

    outside_temperature_threshold:
      name: Buitentemperatuur Drempelwaarde
      description: "Drempelwaarde voor buitenluchttemperatuur. Ventilatoren schakelen aan als de temperatuur onder deze waarde zakt."
      default: 15
      selector:
        number:
          min: 5
          max: 30
          unit_of_measurement: "째C"
          step: 1

    input_custom_action:
      name: Aangepaste Actie
      description: "Definieer een aangepaste actie die wordt uitgevoerd wanneer een temperatuur of moduswijziging plaatsvindt."
      selector:
        action: {}

  trigger:
    - platform: state
      entity_id: !input temp_sensor_woonkamer
      id: temperature_change

    - platform: state
      entity_id: !input weather_sensor
      id: weather_change

    - platform: state
      entity_id: !input vacation_mode
      id: vacation_mode_change

    - platform: state
      entity_id: !input proximity_sensor
      id: proximity_change

  condition:
    - condition: state
      entity_id: !input vacation_mode
      state: "off"

  action:
    - choose:
        - conditions:
            - condition: numeric_state
              entity_id: !input temp_sensor_woonkamer
              below: "{{ states(!input.desired_temp_woonkamer) | float - !input.hysteresis }}"
          sequence:
            - service: switch.turn_on
              target:
                entity_id: !input fan_switch_woonkamer

        - conditions:
            - condition: numeric_state
              entity_id: !input temp_sensor_woonkamer
              above: "{{ states(!input.desired_temp_woonkamer) | float + !input.hysteresis }}"
          sequence:
            - service: switch.turn_off
              target:
                entity_id: !input fan_switch_woonkamer

    - choose:
        - conditions:
            - condition: template
              value_template: >
                {{ state_attr(!input.weather_sensor, 'precipitation') | float > !input.rain_threshold | float }}
            - condition: state
              entity_id: !input disable_rain_shutdown_woonkamer
              state: "on"
          sequence:
            - service: switch.turn_off
              target:
                entity_id: !input fan_switch_woonkamer

    - choose:
        - conditions:
            - condition: template
              value_template: >
                {{ state_attr(!input.weather_sensor, 'temperature') | float < !input.outside_temperature_threshold | float }}
          sequence:
            - service: switch.turn_on
              target:
                entity_id: !input fan_switch_woonkamer

    - choose:
        - conditions:
            - condition: state
              entity_id: !input proximity_sensor
              state: "away"
          sequence:
            - service: switch.turn_off
              target:
                entity_id: !input fan_switch_woonkamer

    - if:
        - condition: template
          value_template: "{{ input_custom_action != none }}"
      then: !input "input_custom_action"

  mode: restart
