blueprint:
  name: "Ventilatiesysteem 5.0"
  description: >
    Dit ventilatiesysteem regelt de ventilatoren op basis van 
    binnentemperatuur, buitentemperatuur en neerslag. 
    De ventilatoren schakelen automatisch op basis van temperatuur en regenstatus.

    Versie: 5.0
    Motregen drempel: 0.3 mm/h. Pas deze waarde aan naar wens.

  domain: automation

  input:
    fan_switch_woonkamer:
      name: Ventilator Woonkamer
      selector:
        entity:
          domain: switch

    temp_sensor_woonkamer:
      name: Temperatuursensor Woonkamer
      selector:
        entity:
          domain: sensor
          device_class: temperature

    desired_temp_woonkamer:
      name: Gewenste temperatuur Woonkamer
      default: 21
      selector:
        number:
          min: 10
          max: 30
          unit_of_measurement: "°C"
          step: 0.5

    disable_rain_shutdown_woonkamer:
      name: Regen uitschakeling Woonkamer
      default: false
      selector:
        boolean: {}

    hysteresis:
      name: Hysteresis
      default: 0.5
      selector:
        number:
          min: 0.1
          max: 5
          unit_of_measurement: "°C"
          step: 0.1

    weather_sensor:
      name: Weersensor
      selector:
        entity:
          domain: weather

    rain_threshold:
      name: Drempelwaarde motregen
      default: 0.3
      selector:
        number:
          min: 0
          max: 5
          unit_of_measurement: "mm/h"
          step: 0.1

  trigger:
    - platform: state
      entity_id: !input temp_sensor_woonkamer
      id: temperature_change

    - platform: state
      entity_id: !input weather_sensor
      id: weather_change

  condition:
    - condition: numeric_state
      entity_id: !input temp_sensor_woonkamer
      below: "{{ states('sensor.' ~ !input.temp_sensor_woonkamer) | float - !input.hysteresis }}"

  action:
    - service: switch.turn_on
      target:
        entity_id: !input fan_switch_woonkamer

    - service: switch.turn_off
      target:
        entity_id: !input fan_switch_woonkamer
