blueprint:
  name: "Ventilatiesysteem versie 5.1"
  description: >
    Dit ventilatiesysteem regelt ventilatoren in meerdere kamers op basis van temperatuur, weersomstandigheden en regensensoren.

  domain: automation

  input:
    fan_switch_woonkamer:
      name: Ventilator Woonkamer
      selector:
        entity:
          domain: switch

    temp_sensor_woonkamer:
      name: Temperatuursensor Woonkamer
      selector:
        entity:
          domain: sensor
          device_class: temperature

    desired_temp_woonkamer:
      name: Gewenste temperatuur Woonkamer
      default: 21
      selector:
        number:
          min: 10
          max: 30
          unit_of_measurement: "°C"
          step: 0.5

    hysteresis:
      name: Hysteresis
      default: 0.5
      selector:
        number:
          min: 0.1
          max: 5
          unit_of_measurement: "°C"
          step: 0.1

    weather_sensor:
      name: Weersensor
      selector:
        entity:
          domain: weather

    rain_threshold:
      name: Drempelwaarde motregen
      default: 0.3
      selector:
        number:
          min: 0
          max: 5
          unit_of_measurement: "mm/h"
          step: 0.1

  variables:
    temp_sensor_woonkamer: !input temp_sensor_woonkamer
    fan_switch_woonkamer: !input fan_switch_woonkamer
    desired_temp_woonkamer: !input desired_temp_woonkamer
    hysteresis: !input hysteresis
    weather_sensor: !input weather_sensor
    rain_threshold: !input rain_threshold

  trigger:
    - platform: state
      entity_id: !input temp_sensor_woonkamer
    - platform: state
      entity_id: !input weather_sensor

  action:
    - choose:
        - conditions:
            - condition: numeric_state
              entity_id: !input temp_sensor_woonkamer
              below: "{{ desired_temp_woonkamer - hysteresis }}"
          sequence:
            - service: switch.turn_on
              target:
                entity_id: !input fan_switch_woonkamer
        - conditions:
            - condition: numeric_state
              entity_id: !input temp_sensor_woonkamer
              above: "{{ desired_temp_woonkamer + hysteresis }}"
          sequence:
            - service: switch.turn_off
              target:
                entity_id: !input fan_switch_woonkamer

    - choose:
        - conditions:
            - condition: template
              value_template: "{{ state_attr(weather_sensor, 'precipitation') | float > rain_threshold }}"
          sequence:
            - service: switch.turn_off
              target:
                entity_id: !input fan_switch_woonkamer
