blueprint:
  name: Tablet Oplaadbeheer
  description: >
    Laadt de tablet op als de batterij onder een drempel komt en stopt als deze vol genoeg is.
    Versie: 1.1
    Changelog:
      - Versie 1.0: Initiële release.
      - Versie 1.1: Secties toegevoegd voor oplaad- en batterijinstellingen.

  domain: automation
  input:
    tablet_settings:
      name: Tablet Instellingen
      description: Instellingen voor de tablet en batterij.
      type: section
      options:
        tablet_battery:
          name: Tablet Batterij Sensor
          description: Selecteer de batterijsensor van je tablet.
          selector:
            entity:
              domain: sensor
    charging_settings:
      name: Oplaadinstellingen
      description: Stel de oplaadschakelaar en drempels in.
      type: section
      options:
        charge_switch:
          name: Oplaad Schakelaar
          description: Selecteer de schakelaar om het opladen te starten en te stoppen.
          selector:
            entity:
              domain: switch
        min_battery:
          name: Minimum batterijpercentage
          description: Start met opladen wanneer het batterijpercentage onder dit percentage komt.
          default: 20
          selector:
            number:
              min: 1
              max: 100
              mode: slider
              unit_of_measurement: "%"
        max_battery:
          name: Maximum batterijpercentage
          description: Stop met opladen wanneer het batterijpercentage dit percentage bereikt.
          default: 90
          selector:
            number:
              min: 1
              max: 100
              mode: slider
              unit_of_measurement: "%"

trigger:
  - platform: numeric_state
    entity_id: !input tablet_battery
    below: !input min_battery

action:
  - service: switch.turn_on
    target:
      entity_id: !input charge_switch

mode: single

trigger:
  - platform: numeric_state
    entity_id: !input tablet_battery
    above: !input max_battery

action:
  - service: switch.turn_off
    target:
      entity_id: !input charge_switch

mode: single
