blueprint:
  name: Insectenlampen Automatisering
  description: Automatiseert de werking van insectenlampen op basis van verschillende sensoren en instellingen.
  domain: automation
  input:
    # Sensoren
    weather_sensor:
      name: Weer Sensor
      description: De weer sensor voor het monitoren van temperatuur en luchtvochtigheid.
      selector:
        entity:
          domain: weather
    beweging_sensor:
      name: Bewegingssensor
      description: Bewegingssensor om te detecteren of er activiteit is in de kamer.
      selector:
        entity:
          domain: binary_sensor
    uv_straling_sensor:
      name: UV Straling Sensor (optioneel)
      description: Sensor voor UV-straling. Indien beschikbaar, helpt deze sensor te bepalen of de UV-straling binnen een gewenst bereik valt.
      selector:
        entity:
          domain: sensor
    grondtemperatuur_sensor:
      name: Grondtemperatuur Sensor (optioneel)
      description: Sensor voor het meten van de temperatuur van de grond. Dit kan helpen bij het beter begrijpen van de omgevingstemperatuur.
      selector:
        entity:
          domain: sensor
    neerslagintensiteit_sensor:
      name: Neerslagintensiteit Sensor (optioneel)
      description: Sensor voor het meten van neerslagintensiteit. Deze sensor is belangrijk om te weten of er neerslag is die de werking van de lamp kan beïnvloeden.
      selector:
        entity:
          domain: sensor
    neerslagverwachting_sensor:
      name: Neerslagverwachting Sensor (optioneel)
      description: Sensor voor neerslagverwachting. Dit helpt bij het inschatten van toekomstige weersomstandigheden.
      selector:
        entity:
          domain: sensor

    # Instellingen
    insectenlamp:
      name: Insectenlamp
      description: De insectenlamp die je wilt automatiseren.
      selector:
        entity:
          domain: switch

    vakantieschakelaar:
      name: Vakantieschakelaar
      description: Schakelaar die aangeeft of je op vakantie bent. Tijdens vakantie kan een andere werking van de lampen vereist zijn.
      selector:
        entity:
          domain: switch

    seizoensmodus_schakelaar:
      name: Seizoensmodus Schakelaar
      description: Schakelaar om de seizoensmodus in te stellen (zomer of winter). Dit beïnvloedt hoe de sensoren reageren op temperatuur en luchtvochtigheid.
      selector:
        entity:
          domain: switch

    temperatuur_min:
      name: Minimale Temperatuur
      description: De minimale temperatuur waarbij de insectenlamp moet worden ingeschakeld.
      default: 20
      selector:
        number:
          min: 0
          max: 50
          unit_of_measurement: '°C'

    temperatuur_max:
      name: Maximale Temperatuur
      description: De maximale temperatuur waarbij de insectenlamp moet worden ingeschakeld.
      default: 35
      selector:
        number:
          min: 0
          max: 50
          unit_of_measurement: '°C'

    luchtvochtigheid_min:
      name: Minimale Luchtvochtigheid
      description: De minimale luchtvochtigheid waarbij de insectenlamp moet worden ingeschakeld.
      default: 60
      selector:
        number:
          min: 0
          max: 100
          unit_of_measurement: '%'

    luchtvochtigheid_max:
      name: Maximale Luchtvochtigheid
      description: De maximale luchtvochtigheid waarbij de insectenlamp moet worden ingeschakeld.
      default: 90
      selector:
        number:
          min: 0
          max: 100
          unit_of_measurement: '%'

    uv_min:
      name: Minimale UV Straling
      description: De minimale UV-straling waarbij de insectenlamp moet worden ingeschakeld.
      default: 200
      selector:
        number:
          min: 0
          max: 1000
          unit_of_measurement: 'W/m²'

    uv_max:
      name: Maximale UV Straling
      description: De maximale UV-straling waarbij de insectenlamp moet worden ingeschakeld.
      default: 800
      selector:
        number:
          min: 0
          max: 1000
          unit_of_measurement: 'W/m²'

    vakantieschakelaar_tijd:
      name: Tijd aan tijdens vakantie
      description: Het aantal minuten dat de lampen aan mogen zijn per dag tijdens de vakantie.
      default: 5
      selector:
        number:
          min: 0
          max: 60
          unit_of_measurement: 'min'

    zomer_temperatuur_min:
      name: Minimale Temperatuur Zomer
      description: Minimale temperatuur voor zomermodus. Deze waarde wordt gebruikt om te bepalen of de lampen aan moeten zijn tijdens de zomer.
      default: 20
      selector:
        number:
          min: 0
          max: 50
          unit_of_measurement: '°C'

    zomer_temperatuur_max:
      name: Maximale Temperatuur Zomer
      description: Maximale temperatuur voor zomermodus. Deze waarde wordt gebruikt om te bepalen of de lampen aan moeten zijn tijdens de zomer.
      default: 35
      selector:
        number:
          min: 0
          max: 50
          unit_of_measurement: '°C'

    winter_temperatuur_max:
      name: Maximale Temperatuur Winter
      description: Maximale temperatuur voor wintermodus. Deze waarde wordt gebruikt om te bepalen of de lampen aan moeten zijn tijdens de winter.
      default: 19
      selector:
        number:
          min: 0
          max: 50
          unit_of_measurement: '°C'

    winter_luchtvochtigheid_max:
      name: Maximale Luchtvochtigheid Winter
      description: Maximale luchtvochtigheid voor wintermodus. Deze waarde wordt gebruikt om te bepalen of de lampen aan moeten zijn tijdens de winter.
      default: 60
      selector:
        number:
          min: 0
          max: 100
          unit_of_measurement: '%'

automation:
  trigger:
    - platform: state
      entity_id: !input 'weather_sensor'
      attribute: temperature
    - platform: state
      entity_id: !input 'weather_sensor'
      attribute: humidity
    - platform: state
      entity_id: !input 'uv_straling_sensor'
      attribute: value
    - platform: state
      entity_id: !input 'beweging_sensor'
    - platform: state
      entity_id: !input 'vakantieschakelaar'
    - platform: state
      entity_id: !input 'seizoensmodus_schakelaar'

  condition:
    - condition: or
      conditions:
        - condition: state
          entity_id: !input 'vakantieschakelaar'
          state: 'on'
        - condition: and
          conditions:
            - condition: numeric_state
              entity_id: !input 'weather_sensor'
              attribute: temperature
              above: !input 'temperatuur_min'
            - condition: numeric_state
              entity_id: !input 'weather_sensor'
              attribute: temperature
              below: !input 'temperatuur_max'
            - condition: numeric_state
              entity_id: !input 'weather_sensor'
              attribute: humidity
              above: !input 'luchtvochtigheid_min'
            - condition: numeric_state
              entity_id: !input 'weather_sensor'
              attribute: humidity
              below: !input 'luchtvochtigheid_max'
            - condition: or
              conditions:
                - condition: numeric_state
                  entity_id: !input 'uv_straling_sensor'
                  above: !input 'uv_min'
                  below: !input 'uv_max'
                - condition: state
                  entity_id: !input 'beweging_sensor'
                  state: 'on'

  action:
    - choose:
        - conditions:
            - condition: state
              entity_id: !input 'vakantieschakelaar'
              state: 'on'
          sequence:
            - service: switch.turn_on
              target:
                entity_id: !input 'insectenlamp'
            - delay: !input 'vakantieschakelaar_tijd'
            - service: switch.turn_off
              target:
                entity_id: !input 'insectenlamp'
        - conditions:
            - condition: state
              entity_id: !input 'beweging_sensor'
              state: 'on'
          sequence:
            - service: switch.turn_on
              target:
                entity_id: !input 'insectenlamp'
            - delay:
                minutes: 30  # Voorbeeld tijd, kan worden aangepast
            - service: switch.turn_off
              target:
                entity_id: !input 'insectenlamp'
        - conditions:
            - condition: state
              entity_id: !input 'seizoensmodus_schakelaar'
              state: 'on'
          sequence:
            - service: switch.turn_on
              target:
                entity_id: !input 'insectenlamp'

  mode: single
