blueprint:
  name: Insectenlamp Automatisering
  description: Automatisering van insectenlampen op basis van weergegevens en tijdsinstellingen.
  domain: automation
  input:
    insectenlamp:
      name: Insectenlamp
      description: De entiteit van de insectenlamp.
      selector:
        entity:
          domain: switch

    buienradar_sensor:
      name: Buienradar Weer Sensor
      description: De weer sensor van Buienradar.
      selector:
        entity:
          domain: weather

    bewegingssensor:
      name: Bewegingssensor
      description: De bewegingssensor die de aanwezigheid detecteert.
      selector:
        entity:
          domain: binary_sensor

    vakantie_modus:
      name: Vakantie Modus
      description: De schakelaar voor vakantie modus.
      selector:
        entity:
          domain: input_boolean

    seizoensmodus:
      name: Seizoensmodus
      description: De schakelaar voor seizoensmodus.
      selector:
        entity:
          domain: input_select

    app_aanwezigheid:
      name: Automatische Aanwezigheidsdetectie
      description: De aanwezigheidssensor van de Home Assistant app.
      selector:
        entity:
          domain: binary_sensor

    handmatige_aanwezigheid:
      name: Handmatige Aanwezigheidsdetectie
      description: De handmatige aanwezigheidssensor, zoals een beeldscherm schakelaar.
      selector:
        entity:
          domain: binary_sensor

    noodbediening:
      name: Noodbediening Insectenlampen
      description: De noodbediening voor de insectenlampen.
      selector:
        entity:
          domain: input_boolean

    noodbediening_timer:
      name: Noodbediening Timer
      description: De timer voor noodbediening van insectenlampen.
      selector:
        entity:
          domain: timer

    temperatuur_min:
      name: Minimum Temperatuur
      description: Minimum temperatuur voor het inschakelen van de lamp.
      default: 20
      selector:
        number:
          min: 10
          max: 35
          step: 1
          unit_of_measurement: "°C"

    temperatuur_max:
      name: Maximum Temperatuur
      description: Maximum temperatuur voor het inschakelen van de lamp.
      default: 35
      selector:
        number:
          min: 10
          max: 35
          step: 1
          unit_of_measurement: "°C"

    luchtvochtigheid_min:
      name: Minimum Luchtvochtigheid
      description: Minimum luchtvochtigheid voor het inschakelen van de lamp.
      default: 50
      selector:
        number:
          min: 0
          max: 100
          step: 1
          unit_of_measurement: "%"

    luchtvochtigheid_max:
      name: Maximum Luchtvochtigheid
      description: Maximum luchtvochtigheid voor het inschakelen van de lamp.
      default: 90
      selector:
        number:
          min: 0
          max: 100
          step: 1
          unit_of_measurement: "%"

    uv_min:
      name: Minimum UV Straling
      description: Minimum UV straling voor het inschakelen van de lamp.
      default: 200
      selector:
        number:
          min: 0
          max: 1000
          step: 1
          unit_of_measurement: "W/m²"

    uv_max:
      name: Maximum UV Straling
      description: Maximum UV straling voor het inschakelen van de lamp.
      default: 300
      selector:
        number:
          min: 0
          max: 1000
          step: 1
          unit_of_measurement: "W/m²"

    regen_min:
      name: Minimum Neerslag
      description: Minimum neerslag voor het inschakelen van de lamp.
      default: 0
      selector:
        number:
          min: 0
          max: 100
          step: 0.1
          unit_of_measurement: "mm"

    regen_max:
      name: Maximum Neerslag
      description: Maximum neerslag voor het inschakelen van de lamp.
      default: 10
      selector:
        number:
          min: 0
          max: 100
          step: 0.1
          unit_of_measurement: "mm"

trigger:
  - platform: state
    entity_id: !input 'insectenlamp'
    to: 'on'
    id: 'insectenlamp_schakelaar'

condition:
  - condition: and
    conditions:
      - condition: template
        value_template: >
          {% set weather = states('weather.buienradar') %}
          {% set temperature = weather.attributes.temperature | float %}
          {% set humidity = weather.attributes.humidity | float %}
          {% set uv = state_attr('sensor.straling', 'value') | float %}
          {% set rain = state_attr('sensor.neerslagintensiteit', 'value') | float %}
          {% set mode = states('input_select.seizoensmodus') %}
          
          {% if mode == 'Zomer' %}
            {{ temperature >= (temperature_min | int) and temperature <= (temperature_max | int) and
               humidity >= (luchtvochtigheid_min | int) and humidity <= (luchtvochtigheid_max | int) and
               uv >= (uv_min | int) and uv <= (uv_max | int) and
               rain <= (regen_max | int) }}
          {% elif mode == 'Winter' %}
            {{ temperature <= (temperature_max | int) and
               humidity >= (luchtvochtigheid_min | int) and humidity <= (luchtvochtigheid_max | int) and
               uv <= (uv_max | int) and
               rain <= (regen_max | int) }}
          {% else %}
            {{ false }}
          {% endif %}

action:
  - choose:
      - conditions:
          - condition: state
            entity_id: !input 'noodbediening'
            state: 'on'
        sequence:
          - service: switch.turn_off
            target:
              entity_id: !input 'insectenlamp'
          - delay: '00:01:00'
          - service: switch.turn_on
            target:
              entity_id: !input 'insectenlamp'
    default:
      - service: switch.turn_off
        target:
          entity_id: !input 'insectenlamp'
