blueprint:
  name: Insectenlamp Automatisering
  description: Automatisering voor het schakelen van insectenlampen gebaseerd op verschillende sensoren en instellingen.
  domain: automation
  input:
    # Weer Sensor
    weather_sensor:
      name: Weer Sensor
      description: Deze sensor levert gegevens over temperatuur en luchtvochtigheid.
      selector:
        entity:
          domain: weather

    # Bewegingssensor
    motion_sensor:
      name: Bewegingssensor
      description: Detecteert beweging in de ruimte en schakelt de lamp in bij aanwezigheid.
      selector:
        entity:
          domain: binary_sensor

    # Vakantieschakelaar
    vacation_switch:
      name: Vakantieschakelaar
      description: Geeft aan of je op vakantie bent en past de lampinstellingen aan.
      selector:
        entity:
          domain: switch

    # Seizoensmodus Schakelaar
    seasonal_mode_switch:
      name: Seizoensmodus Schakelaar
      description: Stelt de modus in op zomer of winter en past de drempelwaarden aan.
      selector:
        entity:
          domain: switch

    # Extra optionele sensoren
    straling_sensor:
      name: UV-Straling Sensor
      description: Meet de UV-straling, wat belangrijk is voor het bepalen van de effectiviteit van insectenbestrijding.
      selector:
        entity:
          domain: sensor

    grondtemperatuur_sensor:
      name: Grondtemperatuur Sensor
      description: Meet de grondtemperatuur, wat kan helpen bij het bepalen van de activiteit van insecten.
      selector:
        entity:
          domain: sensor

    neerslagintensiteit_sensor:
      name: Neerslagintensiteit Sensor
      description: Meet de hoeveelheid regenval per uur. Kan helpen bij het bepalen van de effectiviteit van de lampen.
      selector:
        entity:
          domain: sensor

    neerslagverwachting_sensor:
      name: Neerslagverwachting Sensor
      description: Geeft de verwachte hoeveelheid neerslag voor de komende tijd. Belangrijk voor het plannen van de werking van de lampen.
      selector:
        entity:
          domain: sensor

  trigger:
    - platform: state
      entity_id: !input weather_sensor
    - platform: state
      entity_id: !input motion_sensor
    - platform: state
      entity_id: !input vacation_switch
    - platform: state
      entity_id: !input seasonal_mode_switch

  condition:
    - condition: template
      value_template: >
        {% set weather_sensor = states(!input weather_sensor) %}
        {% set temp = weather_sensor.attributes.temperature %}
        {% set humidity = weather_sensor.attributes.humidity %}
        {% set straling = states(!input straling_sensor) %}
        {% set grondtemp = states(!input grondtemperatuur_sensor) %}
        {% set neerslagintensiteit = states(!input neerslagintensiteit_sensor) %}
        {% set neerslagverwachting = states(!input neerslagverwachting_sensor) %}

        # Voorbeeld drempelwaarden
        {% set temp_min = 20 %}
        {% set temp_max = 35 %}
        {% set humidity_min = 60 %}
        {% set straling_min = 200 %}
        {% set grondtemp_min = 15 %}
        {% set neerslagintensiteit_max = 10 %}
        {% set neerslagverwachting_max = 5 %}

        # Controleer of waarden binnen de drempelwaarden vallen
        temp >= temp_min and temp <= temp_max and
        humidity >= humidity_min and
        straling.attributes.value >= straling_min and
        grondtemp.attributes.value >= grondtemp_min and
        neerslagintensiteit.attributes.value <= neerslagintensiteit_max and
        neerslagverwachting.attributes.value <= neerslagverwachting_max

  action:
    - choose:
        - conditions:
            - condition: state
              entity_id: !input vacation_switch
              state: 'on'
          sequence:
            - service: switch.turn_off
              target:
                entity_id: !input motion_sensor
            - service: logbook.log
              data:
                name: "Insectenlamp Automatisering"
                message: "Vakantieschakelaar is actief, lampen worden uitgeschakeld."

        - conditions:
            - condition: state
              entity_id: !input seasonal_mode_switch
              state: 'summer'
          sequence:
            - service: light.turn_on
              target:
                entity_id: !input light_insectenlamp
            - service: logbook.log
              data:
                name: "Insectenlamp Automatisering"
                message: "Zomer modus geactiveerd, lampen worden ingeschakeld."

        - conditions:
            - condition: state
              entity_id: !input seasonal_mode_switch
              state: 'winter'
          sequence:
            - service: light.turn_off
              target:
                entity_id: !input light_insectenlamp
            - service: logbook.log
              data:
                name: "Insectenlamp Automatisering"
                message: "Winter modus geactiveerd, lampen worden uitgeschakeld."

    - service: timer.start
      target:
        entity_id: timer.insectenlamp_timer
      data:
        duration: '00:05:00'
