blueprint:
  name: Insectenlampen Automatisering
  description: Automatisering voor insectenlampen met noodbediening en schakeltijden.
  domain: automation
  input:
    insectenlamp:
      name: Insectenlamp Entiteit
      selector:
        entity:
          domain: switch
    minimum_tijd:
      name: Minimum Tijd (minuten)
      selector:
        number:
          min: 5
          max: 120
          step: 1
          unit_of_measurement: 'min'
    maximum_tijd:
      name: Maximum Tijd (minuten)
      selector:
        number:
          min: 5
          max: 120
          step: 1
          unit_of_measurement: 'min'
    noodbediening:
      name: Noodbediening Insectenlampen
      selector:
        entity:
          domain: input_boolean
    timer:
      name: Noodbediening Timer
      selector:
        entity:
          domain: timer

trigger:
  - platform: state
    entity_id: !input noodbediening
    to: 'on'

action:
  - choose:
      - conditions:
          - condition: state
            entity_id: !input noodbediening
            state: 'on'
        sequence:
          - service: timer.start
            data:
              entity_id: !input timer
              duration: '00:60:00'
          - service: switch.turn_off
            target:
              entity_id: !input insectenlamp
    default:
      - service: switch.turn_on
        target:
          entity_id: !input insectenlamp
      - service: timer.start
        data:
          entity_id: !input timer
          duration: '00:60:00'

mode: single
