blueprint:
  name: Insectenlampen Automatisering
  description: Automatiseert de werking van insectenlampen op basis van verschillende sensoren en instellingen.
  domain: automation
  input:
    insectenlamp:
      name: Insectenlamp
      description: De insectenlamp die je wilt automatiseren.
      selector:
        entity:
          domain: switch

    weather_sensor:
      name: Weer Sensor
      description: De weer sensor voor buienradar.
      selector:
        entity:
          domain: weather

    beweging_sensor:
      name: Bewegingssensor
      description: Bewegingssensor in de kamer.
      selector:
        entity:
          domain: binary_sensor

    vakantieschakelaar:
      name: Vakantieschakelaar
      description: Schakelaar voor vakanties.
      selector:
        entity:
          domain: switch

    seizoensmodus_schakelaar:
      name: Seizoensmodus Schakelaar
      description: Schakelaar voor het instellen van seizoensmodus.
      selector:
        entity:
          domain: switch

    uv_straling_sensor:
      name: UV Straling Sensor (optioneel)
      description: Sensor voor UV-straling, indien beschikbaar.
      selector:
        entity:
          domain: sensor

    grondtemperatuur_sensor:
      name: Grondtemperatuur Sensor (optioneel)
      description: Sensor voor grondtemperatuur, indien beschikbaar.
      selector:
        entity:
          domain: sensor

    neerslagintensiteit_sensor:
      name: Neerslagintensiteit Sensor (optioneel)
      description: Sensor voor neerslagintensiteit, indien beschikbaar.
      selector:
        entity:
          domain: sensor

    neerslagverwachting_sensor:
      name: Neerslagverwachting Sensor (optioneel)
      description: Sensor voor neerslagverwachting, indien beschikbaar.
      selector:
        entity:
          domain: sensor

    # Instellingen
    temperatuur_min:
      name: Minimale Temperatuur
      description: Minimale temperatuur voor activering van de lampen.
      default: 20
      selector:
        number:
          min: 0
          max: 50
          unit_of_measurement: °C

    temperatuur_max:
      name: Maximale Temperatuur
      description: Maximale temperatuur voor activering van de lampen.
      default: 35
      selector:
        number:
          min: 0
          max: 50
          unit_of_measurement: °C

    luchtvochtigheid_min:
      name: Minimale Luchtvochtigheid
      description: Minimale luchtvochtigheid voor activering van de lampen.
      default: 60
      selector:
        number:
          min: 0
          max: 100
          unit_of_measurement: %

    luchtvochtigheid_max:
      name: Maximale Luchtvochtigheid
      description: Maximale luchtvochtigheid voor activering van de lampen.
      default: 90
      selector:
        number:
          min: 0
          max: 100
          unit_of_measurement: %

    uv_min:
      name: Minimale UV Straling
      description: Minimale UV-straling om de lampen uit te schakelen.
      default: 200
      selector:
        number:
          min: 0
          max: 1000
          unit_of_measurement: W/m²

    uv_max:
      name: Maximale UV Straling
      description: Maximale UV-straling om de lampen aan te zetten.
      default: 800
      selector:
        number:
          min: 0
          max: 1000
          unit_of_measurement: W/m²

    # Instellingen voor vakantieschakelaar
    vakantieschakelaar_tijd:
      name: Tijd aan tijdens vakantie
      description: Tijd in minuten dat de lampen aan mogen zijn per dag tijdens de vakantie.
      default: 5
      selector:
        number:
          min: 0
          max: 60
          unit_of_measurement: min

    # Seizoensmodus
    zomer_temperatuur_min:
      name: Minimale Temperatuur Zomer
      description: Minimale temperatuur voor zomermodus.
      default: 20
      selector:
        number:
          min: 0
          max: 50
          unit_of_measurement: °C

    zomer_temperatuur_max:
      name: Maximale Temperatuur Zomer
      description: Maximale temperatuur voor zomermodus.
      default: 35
      selector:
        number:
          min: 0
          max: 50
          unit_of_measurement: °C

    winter_temperatuur_max:
      name: Maximale Temperatuur Winter
      description: Maximale temperatuur voor wintermodus.
      default: 19
      selector:
        number:
          min: 0
          max: 50
          unit_of_measurement: °C

    winter_luchtvochtigheid_max:
      name: Maximale Luchtvochtigheid Winter
      description: Maximale luchtvochtigheid voor wintermodus.
      default: 60
      selector:
        number:
          min: 0
          max: 100
          unit_of_measurement: %

automation:
  trigger:
    - platform: state
      entity_id: !input 'weather_sensor'
      attribute: temperature
    - platform: state
      entity_id: !input 'weather_sensor'
      attribute: humidity
    - platform: state
      entity_id: !input 'uv_straling_sensor'
      attribute: value
    - platform: state
      entity_id: !input 'beweging_sensor'
    - platform: state
      entity_id: !input 'vakantieschakelaar'
    - platform: state
      entity_id: !input 'seizoensmodus_schakelaar'

  condition:
    - condition: or
      conditions:
        - condition: state
          entity_id: !input 'vakantieschakelaar'
          state: 'on'
        - condition: and
          conditions:
            - condition: numeric_state
              entity_id: !input 'weather_sensor'
              attribute: temperature
              above: !input 'temperatuur_min'
            - condition: numeric_state
              entity_id: !input 'weather_sensor'
              attribute: temperature
              below: !input 'temperatuur_max'
            - condition: numeric_state
              entity_id: !input 'weather_sensor'
              attribute: humidity
              above: !input 'luchtvochtigheid_min'
            - condition: numeric_state
              entity_id: !input 'weather_sensor'
              attribute: humidity
              below: !input 'luchtvochtigheid_max'
            - condition: or
              conditions:
                - condition: numeric_state
                  entity_id: !input 'uv_straling_sensor'
                  above: !input 'uv_min'
                  below: !input 'uv_max'
                - condition: state
                  entity_id: !input 'beweging_sensor'
                  state: 'on'
  
  action:
    - choose:
        - conditions:
            - condition: state
              entity_id: !input 'vakantieschakelaar'
              state: 'on'
          sequence:
            - service: switch.turn_on
              target:
                entity_id: !input 'insectenlamp'
            - delay: !input 'vakantieschakelaar_tijd'
            - service: switch.turn_off
              target:
                entity_id: !input 'insectenlamp'
        - conditions:
            - condition: state
              entity_id: !input 'beweging_sensor'
              state: 'on'
          sequence:
            - service: switch.turn_on
              target:
                entity_id: !input 'insectenlamp'
            - delay:
                minutes: 30  # Voorbeeld tijd, kan worden aangepast
            - service: switch.turn_off
              target:
                entity_id: !input 'insectenlamp'
        - conditions:
            - condition: state
              entity_id: !input 'seizoensmodus_schakelaar'
              state: 'on'
          sequence:
            - service: switch.turn_on
              target:
                entity_id: !input 'insectenlamp'
  
  mode: single
