blueprint:
  name: Automatisering Insectenverdelger Lampen
  description: Automatisering voor insectenverdelger lampen op basis van weersomstandigheden, tijdsblokken, en aanwezigheid.
  domain: automation
  input:
    insectenlamp_1:
      name: Insectenlamp Keuken
      description: Entiteit van de insectenlamp in de keuken
      selector:
        entity:
          domain: switch
    insectenlamp_2:
      name: Insectenlamp Kantoorruimte
      description: Entiteit van de insectenlamp in de kantoorruimte
      selector:
        entity:
          domain: switch
    weer_sensor:
      name: Buienradar Weersensor
      description: Selecteer de Buienradar sensor voor weersomstandigheden
      selector:
        entity:
          domain: weather
    knop_beeldscherm:
      name: Beeldscherm Aan/Uit Knop
      description: Entiteit van de knop die het beeldscherm inschakelt
      selector:
        entity:
          domain: switch
    bewegingssensor_keuken:
      name: Bewegingssensor Keuken
      description: Bewegingssensor nabij de keuken
      selector:
        entity:
          domain: binary_sensor
          device_class: motion
    bewegingssensor_kantoor:
      name: Bewegingssensor Kantoor Overloop
      description: Bewegingssensor nabij de kantoorruimte
      selector:
        entity:
          domain: binary_sensor
          device_class: motion
    aanwezigheidssensor:
      name: Aanwezigheidsdetectie (Optioneel)
      description: Gebruik Home Assistant app voor aanwezigheid van bewoners
      selector:
        entity:
          domain: person
          multiple: true
    vakantie_mode:
      name: Vakantiemodus Schakelaar
      description: Schakelaar om de vakantiemodus in of uit te schakelen
      selector:
        entity:
          domain: input_boolean
    seizoen_mode:
      name: Seizoensmodus Schakelaar
      description: Schakelaar om de seizoensmodus (zomer/winter) in te stellen
      selector:
        entity:
          domain: input_boolean

trigger:
  - platform: time
    at: "06:00:00"
  - platform: time
    at: "12:00:00"
  - platform: time
    at: "18:00:00"
  - platform: time
    at: "22:00:00"

condition:
  - condition: state
    entity_id: !input vakantie_mode
    state: "off"
  - condition: template
    value_template: >
      {% set uv_index = states('sensor.{{ weer_sensor }}_uv_index') | float %}
      {% set humidity = states('sensor.{{ weer_sensor }}_humidity') | float %}
      {% set temperature = states('sensor.{{ weer_sensor }}_temperature') | float %}
      {% if is_state('input_boolean.{{ seizoen_mode }}', 'on') %}
        {{ uv_index < 5 and humidity > 60 and temperature > 15 }}
      {% else %}
        {{ uv_index < 3 and humidity > 70 and temperature > 10 }}
      {% endif %}

action:
  - choose:
      - conditions:
          - condition: time
            after: "06:00:00"
            before: "12:00:00"
        sequence:
          - service: switch.turn_on
            target:
              entity_id: !input insectenlamp_1
            data:
              transition: 15
      - conditions:
          - condition: time
            after: "12:00:00"
            before: "18:00:00"
        sequence:
          - service: switch.turn_on
            target:
              entity_id: !input insectenlamp_1
              entity_id: !input insectenlamp_2
            data:
              transition: 15
      - conditions:
          - condition: time
            after: "18:00:00"
            before: "22:00:00"
        sequence:
          - service: switch.turn_on
            target:
              entity_id: !input insectenlamp_1
              entity_id: !input insectenlamp_2
            data:
              transition: 30
      - conditions:
          - condition: time
            after: "22:00:00"
            before: "00:00:00"
        sequence:
          - service: switch.turn_on
            target:
              entity_id: !input insectenlamp_2
            data:
              transition: 30
  - service: switch.turn_off
    target:
      entity_id:
        - !input insectenlamp_1
        - !input insectenlamp_2
    data:
      transition: 5

mode: restart
